import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

type LanguageProviderProps = {
  children: React.ReactNode;
  defaultLanguage?: Language;
};

type LanguageProviderState = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageProviderContext = createContext<LanguageProviderState | undefined>(undefined);

// Translation dictionaries
const translations = {
  en: {
    // Common
    "app.name": "A.Z Finance Hub",
    "app.subtitle": "Vision 2040",
    "app.copyright": "© 2025 A.Z Finance",
    "common.sar": "SAR",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.investments": "Investments",
    "nav.cashflows": "Cashflows",
    "nav.analytics": "Analytics",
    "nav.reinvestment": "Reinvestment",
    "nav.timeline": "Timeline",
    "nav.alerts": "Alerts",
    "nav.help": "Help & Guide",
    "nav.settings": "Settings",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Welcome to your personal investment management hub",
    "dashboard.totalCapital": "Total Capital",
    "dashboard.totalReturns": "Total Returns",
    "dashboard.averageIrr": "Average IRR",
    "dashboard.progressTo2040": "Progress to 2040",
    "dashboard.portfolioPerformance": "Portfolio Performance",
    "dashboard.upcomingCashflows": "Upcoming Cashflows",
    "dashboard.recentInvestments": "Recent Investments",
    "dashboard.noDataYet": "No data available yet",
    "dashboard.availableCash": "Available Cash",
    "dashboard.totalCashBalance": "Total Cash Balance",
    "dashboard.reinvestedAmount": "Reinvested",
    "dashboard.averageDuration": "Avg Duration",
    "dashboard.distressedCount": "Distressed",
    "dashboard.days": "days",
    "dashboard.investments": "investments",
    "dashboard.cashManagement": "Cash Management",
    "dashboard.additionalMetrics": "Additional Metrics",
    
    // Investments
    "investments.title": "Investments",
    "investments.subtitle": "Manage your investment portfolio across multiple platforms",
    "investments.addInvestment": "Add Investment",
    "investments.noInvestmentsYet": "No investments yet",
    "investments.noInvestmentsDesc": "Start building your portfolio by adding your first investment opportunity",
    "investments.addFirstInvestment": "Add Your First Investment",
    "investments.editInvestment": "Edit Investment",
    "investments.amount": "Amount",
    "investments.irr": "Expected IRR",
    "investments.expectedIrr": "Expected IRR",
    "investments.risk": "Risk",
    "investments.startDate": "Start Date",
    "investments.endDate": "End Date",
    "investments.expectedEndDate": "Expected End Date",
    "investments.actualEndDate": "Actual End Date",
    "investments.status": "Status",
    "investments.riskScore": "Risk Score",
    "investments.daysRemaining": "days remaining",
    "investments.days": "days",
    "investments.delayed": "Delayed",
    "investments.distressed": "Distressed",
    "investments.active": "Active",
    "investments.completed": "Completed",
    "investments.pending": "Pending",
    
    // Cashflows
    "cashflows.title": "Cashflows",
    "cashflows.subtitle": "Track all profit distributions and returns from your investments",
    "cashflows.totalReceived": "Total Received",
    "cashflows.expectedThisQuarter": "Expected This Quarter",
    "cashflows.allCashflows": "All Cashflows",
    "cashflows.date": "Date",
    "cashflows.investment": "Investment",
    "cashflows.platform": "Platform",
    "cashflows.amount": "Amount",
    "cashflows.status": "Status",
    "cashflows.type": "Type",
    "cashflows.received": "Received",
    "cashflows.expected": "Expected",
    "cashflows.upcoming": "Upcoming",
    "cashflows.profit": "Profit",
    "cashflows.principal": "Principal",
    "cashflows.noCashflows": "No cashflows recorded yet",
    "cashflows.inDays": "in {0} days",
    
    // Analytics
    "analytics.title": "Analytics",
    "analytics.subtitle": "Deep insights into your portfolio performance and projections",
    "analytics.returns": "Returns",
    "analytics.allocation": "Allocation",
    "analytics.goals": "Goals",
    "analytics.monthlyReturnsTrend": "Monthly Returns Trend",
    "analytics.portfolioAllocation": "Portfolio Allocation by Platform",
    "analytics.performanceVsTarget": "Performance vs 2040 Target",
    
    // Timeline
    "timeline.title": "Timeline",
    "timeline.subtitle": "Complete history of all investment activities and transactions",
    "timeline.noActivity": "No activity yet",
    "timeline.noActivityDesc": "Your investment timeline will appear here as you add investments and receive distributions",
    "timeline.investmentStarted": "Investment Started",
    "timeline.investmentMatured": "Investment Matured",
    "timeline.profitReceived": "Profit Distribution Received",
    "timeline.newInvestment": "New investment in {0}",
    "timeline.matured": "{0} reached maturity",
    "timeline.payment": "{0} payment received",
    "timeline.investment": "Investment",
    "timeline.cashflow": "Cashflow",
    "timeline.maturity": "Maturity",
    
    // Alerts
    "alerts.title": "Alerts",
    "alerts.subtitle": "Stay updated with important notifications and events",
    "alerts.unread": "{0} unread",
    "alerts.noAlertsYet": "No alerts yet",
    "alerts.noAlertsDesc": "You'll receive notifications here for distributions, maturities, and important events",
    "alerts.markAsRead": "Mark as read",
    "alerts.distribution": "distribution",
    "alerts.maturity": "maturity",
    "alerts.opportunity": "opportunity",
    "alerts.risk": "risk",
    "alerts.success": "Success",
    "alerts.warning": "Warning",
    "alerts.error": "Error",
    "alerts.info": "Info",
    
    // Reinvestment
    "reinvestment.title": "Profit Reinvestment",
    "reinvestment.description": "Track available cash and reinvest your profits strategically",
    "reinvestment.availableCash": "Available Cash",
    "reinvestment.fromDistributions": "From received distributions",
    "reinvestment.totalInvested": "Total Invested",
    "reinvestment.currentCapital": "Current portfolio capital",
    "reinvestment.receivedCount": "Distributions",
    "reinvestment.distributions": "received distributions",
    "reinvestment.opportunitiesTitle": "Reinvestment Opportunities",
    "reinvestment.opportunitiesDescription": "Best performing active investments ranked by expected IRR",
    "reinvestment.noOpportunities": "No active investments available for reinvestment",
    "reinvestment.reinvest": "Reinvest",
    "reinvestment.reinvestIn": "Reinvest in",
    "reinvestment.reinvestDescription": "Enter the amount you want to reinvest into this opportunity",
    "reinvestment.confirmReinvest": "Confirm Reinvestment",
    "reinvestment.recentDistributions": "Recent Distributions",
    "reinvestment.recentDistributionsDescription": "Cash received from your investments",
    "reinvestment.noDistributions": "No distributions received yet",
    
    // Dialog
    "dialog.addInvestment": "Add New Investment",
    "dialog.editInvestment": "Edit Investment",
    "dialog.addInvestmentDesc": "Enter the details of your new investment opportunity",
    "dialog.editInvestmentDesc": "Update the details of your investment",
    "dialog.platform": "Platform",
    "dialog.selectPlatform": "Select a platform",
    "dialog.investmentName": "Investment Name",
    "dialog.investmentNamePlaceholder": "e.g., Sukuk 2025-A",
    "dialog.amountSAR": "Amount (SAR)",
    "dialog.expectedIRR": "Expected IRR (%)",
    "dialog.expectedEndDate": "Expected End Date",
    "dialog.actualEndDate": "Actual End Date",
    "dialog.distributionFrequency": "Distribution Frequency",
    "dialog.quarterly": "Quarterly",
    "dialog.semiAnnual": "Semi-Annual",
    "dialog.annual": "Annual",
    "dialog.cancel": "Cancel",
    "dialog.save": "Save",
    "dialog.saving": "Saving...",
    "dialog.update": "Update Investment",
    "dialog.add": "Add Investment",
    "dialog.error": "Error",
    "dialog.success": "Success",
    "dialog.createError": "Failed to create investment",
    "dialog.updateError": "Failed to update investment",
    
    // Export
    "export.report": "Export",
    "export.monthly": "Monthly Report",
    "export.quarterly": "Quarterly Report",
    
    // View Mode
    "viewMode.pro": "Professional Mode",
    "viewMode.lite": "Lite Mode",
    
    // Settings
    "settings.title": "Settings",
    "settings.description": "Customize your investment hub experience",
    "settings.appearance": "Appearance",
    "settings.appearanceDesc": "Customize the look and feel of your dashboard",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.fontSize": "Font Size",
    "settings.small": "Small",
    "settings.medium": "Medium",
    "settings.large": "Large",
    "settings.viewMode": "View Mode",
    "settings.proMode": "Professional Mode",
    "settings.liteMode": "Lite Mode",
    "settings.proModeDesc": "Full detailed analytics, complete breakdowns, and advanced charts",
    "settings.liteModeDesc": "Simplified interface showing only main metrics and essential information",
    "settings.languageRegion": "Language & Region",
    "settings.languageRegionDesc": "Configure language and regional preferences",
    "settings.language": "Language",
    "settings.currency": "Currency",
    "settings.currencyNote": "Currently SAR (Saudi Riyal) only",
    "settings.investmentGoals": "Investment Goals",
    "settings.investmentGoalsDesc": "Set your financial targets and preferences",
    "settings.targetCapital2040": "Target Capital by 2040",
    "settings.targetCapitalDesc": "Your financial goal for Vision 2040 (in SAR)",
    "settings.autoReinvest": "Auto-Reinvest Profits",
    "settings.autoReinvestDesc": "Automatically reinvest received distributions",
    "settings.platforms": "Platform Management",
    "settings.platformsDesc": "Manage your crowdfunding platforms",
    "settings.existingPlatforms": "Existing Platforms",
    "settings.addNewPlatform": "Add New Platform",
    "settings.platformNamePlaceholder": "Platform name",
    "settings.other": "Other",
    "settings.addPlatform": "Add Platform",
    "settings.saved": "Settings Saved",
    "settings.savedDesc": "Your preferences have been updated successfully",
    "settings.saveError": "Failed to save settings",
    "settings.platformAdded": "Platform Added",
    "settings.platformAddedDesc": "New platform has been added successfully",
    "settings.platformAddError": "Failed to add platform",
    "settings.platformNameRequired": "Platform name is required",
    
    // Help & Guide
    "help.title": "Help & Guide",
    "help.subtitle": "Comprehensive guide to using A.Z Finance Hub",
    "help.gettingStarted": "Getting Started",
    "help.gettingStartedDesc": "Learn the basics of A.Z Finance Hub and how to get started with your investment journey.",
    "help.addingInvestments": "Adding Investments",
    "help.addingInvestmentsDesc": "Navigate to the Investments page and click 'Add Investment'. Fill in details including platform, amount (use +1000 SAR quick button for convenience), expected IRR, risk score, and dates. Select status: Active (ongoing), Pending (not yet started), or Completed (finished).",
    "help.trackingCashflows": "Tracking Cashflows",
    "help.trackingCashflowsDesc": "Monitor all profit distributions and principal returns in the Cashflows section. Filter by status: Received (already paid), Expected (due soon), or Upcoming (scheduled).",
    "help.reinvesting": "Reinvesting Profits",
    "help.reinvestingDesc": "Use the Reinvestment page to view available cash from distributions. Select a high-performing investment and click 'Reinvest' to compound your returns strategically.",
    
    "help.features": "Key Features",
    "help.featuresDesc": "Explore the powerful features of A.Z Finance Hub",
    "help.proLiteMode": "Pro / Lite Mode",
    "help.proLiteModeDesc": "Toggle between Professional Mode (full analytics, detailed breakdowns, advanced charts) and Lite Mode (simplified view with 4 core metrics only). Switch using the icon in the sidebar footer.",
    "help.delayTracking": "Delay & Distressed Tracking",
    "help.delayTrackingDesc": "For completed investments, set the Actual End Date. If delayed beyond Expected End Date, the system calculates delay days. Delays ≥90 days (3 months) automatically flag as 'Distressed' with a red badge.",
    "help.quickInput": "Quick Input (+1000 SAR)",
    "help.quickInputDesc": "When adding investments, use the +1000 SAR button next to the Amount field for fast data entry. Each click adds 1000 SAR to the current value.",
    "help.bilingualSupport": "Bilingual Support",
    "help.bilingualSupportDesc": "Switch between English and Arabic (with RTL support) using the language toggle button. All content, including dates and numbers, adapts to your language choice.",
    
    "help.metrics": "Understanding Metrics",
    "help.metricsDesc": "Key performance indicators explained",
    "help.totalCapital": "Total Capital",
    "help.totalCapitalDesc": "Sum of all investment amounts across your portfolio, including active, pending, and completed investments.",
    "help.totalReturns": "Total Returns",
    "help.totalReturnsDesc": "Sum of all received profit distributions and principal returns from your investments.",
    "help.averageIRR": "Average IRR",
    "help.averageIRRDesc": "Internal Rate of Return - the average expected annual return percentage across your portfolio, weighted by investment amount.",
    "help.progressTo2040": "Progress to 2040",
    "help.progressTo2040Desc": "Percentage of your Vision 2040 target capital achieved, calculated as (Total Returns / Target Capital) × 100.",
    "help.availableCash": "Available Cash",
    "help.availableCashDesc": "Cash ready for reinvestment = Total Cash Balance minus active/pending reinvestments. Completed reinvestments return their capital.",
    "help.distressedInvestments": "Distressed Investments",
    "help.distressedInvestmentsDesc": "Completed investments delayed by 3+ months (≥90 days). These require attention and may indicate platform issues.",
    
    "help.platforms": "Supported Platforms",
    "help.platformsDesc": "Crowdfunding debt platforms integrated into the system",
    "help.sukuk": "Sukuk",
    "help.sukukDesc": "Islamic compliant investment platform offering Sharia-compliant bonds and financing opportunities.",
    "help.manfaa": "Manfa'a",
    "help.manfaaDesc": "Saudi crowdfunding platform for debt-based investments with various risk profiles.",
    "help.lendo": "Lendo",
    "help.lendoDesc": "Peer-to-peer lending platform connecting investors with borrowers for fixed-return investments.",
    "help.addCustomPlatform": "Add Custom Platform",
    "help.addCustomPlatformDesc": "Go to Settings → Platform Management to add additional platforms not in the default list.",
    
    "help.tips": "Tips & Best Practices",
    "help.tipsDesc": "Maximize your experience with these helpful tips",
    "help.tip1": "Regularly Update Actual End Dates",
    "help.tip1Desc": "For completed investments, always set the Actual End Date to track delays and identify problematic platforms.",
    "help.tip2": "Monitor Distressed Investments",
    "help.tip2Desc": "Check for red 'Distressed' badges regularly. Consider reducing exposure to platforms with frequent delays.",
    "help.tip3": "Use Pro Mode for Analysis",
    "help.tip3Desc": "Switch to Professional Mode when reviewing portfolio performance to access detailed charts and cash flow analytics.",
    "help.tip4": "Reinvest Strategically",
    "help.tip4Desc": "Use the Reinvestment page to identify top-performing opportunities sorted by expected IRR before deploying available cash.",
    "help.tip5": "Set Realistic Goals",
    "help.tip5Desc": "In Settings, configure your Vision 2040 target capital to track progress toward your financial objectives.",
    
    "help.settings": "Settings & Customization",
    "help.settingsDesc": "Personalize your investment hub experience",
    "help.appearance": "Appearance Settings",
    "help.appearanceDesc": "Customize theme (Light/Dark), font size (Small/Medium/Large), and view mode. Toggle between Professional Mode (full analytics) and Lite Mode (4 core metrics) to match your preference.",
    "help.languageSettings": "Language & Region",
    "help.languageSettingsDesc": "Switch between English and Arabic with full RTL support. Currency is currently SAR (Saudi Riyal) only. All dates, numbers, and text adapt to your language choice.",
    "help.investmentGoalsSettings": "Investment Goals",
    "help.investmentGoalsSettingsDesc": "Set your Vision 2040 target capital to track long-term financial progress. Enable auto-reinvest to automatically deploy received distributions into new opportunities.",
    "help.platformManagement": "Platform Management",
    "help.platformManagementDesc": "View existing platforms (Sukuk, Manfa'a, Lendo) and add custom platforms. Enter platform name and select type (Sukuk/Manfa'a/Lendo/Other) to expand your investment universe.",
  },
  ar: {
    // Common
    "app.name": "مركز A.Z المالي",
    "app.subtitle": "رؤية 2040",
    "app.copyright": "© 2025 A.Z المالية",
    "common.sar": "ريال",
    
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.investments": "الاستثمارات",
    "nav.cashflows": "التدفقات النقدية",
    "nav.analytics": "التحليلات",
    "nav.reinvestment": "إعادة الاستثمار",
    "nav.timeline": "الخط الزمني",
    "nav.alerts": "التنبيهات",
    "nav.help": "المساعدة والدليل",
    "nav.settings": "الإعدادات",
    
    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.subtitle": "مرحباً بك في مركز إدارة الاستثمارات الشخصي",
    "dashboard.totalCapital": "رأس المال الإجمالي",
    "dashboard.totalReturns": "إجمالي العوائد",
    "dashboard.averageIrr": "متوسط العائد الداخلي",
    "dashboard.progressTo2040": "التقدم نحو 2040",
    "dashboard.portfolioPerformance": "أداء المحفظة",
    "dashboard.upcomingCashflows": "التدفقات القادمة",
    "dashboard.recentInvestments": "الاستثمارات الأخيرة",
    "dashboard.noDataYet": "لا توجد بيانات متاحة بعد",
    "dashboard.availableCash": "النقد المتاح",
    "dashboard.totalCashBalance": "الرصيد النقدي الإجمالي",
    "dashboard.reinvestedAmount": "المعاد استثماره",
    "dashboard.averageDuration": "متوسط المدة",
    "dashboard.distressedCount": "متعثرة",
    "dashboard.days": "يوم",
    "dashboard.investments": "استثمارات",
    "dashboard.cashManagement": "إدارة النقد",
    "dashboard.additionalMetrics": "مقاييس إضافية",
    
    // Investments
    "investments.title": "الاستثمارات",
    "investments.subtitle": "إدارة محفظة استثماراتك عبر منصات متعددة",
    "investments.addInvestment": "إضافة استثمار",
    "investments.noInvestmentsYet": "لا توجد استثمارات بعد",
    "investments.noInvestmentsDesc": "ابدأ ببناء محفظتك بإضافة أول فرصة استثمارية",
    "investments.addFirstInvestment": "أضف استثمارك الأول",
    "investments.editInvestment": "تعديل الاستثمار",
    "investments.amount": "المبلغ",
    "investments.irr": "العائد المتوقع",
    "investments.expectedIrr": "العائد المتوقع",
    "investments.risk": "المخاطرة",
    "investments.startDate": "تاريخ البداية",
    "investments.endDate": "تاريخ النهاية",
    "investments.expectedEndDate": "تاريخ الانتهاء المتوقع",
    "investments.actualEndDate": "تاريخ الانتهاء الفعلي",
    "investments.status": "الحالة",
    "investments.riskScore": "درجة المخاطرة",
    "investments.daysRemaining": "أيام متبقية",
    "investments.days": "أيام",
    "investments.delayed": "متأخر",
    "investments.distressed": "متعثر",
    "investments.active": "نشط",
    "investments.completed": "مكتمل",
    "investments.pending": "قيد الانتظار",
    
    // Cashflows
    "cashflows.title": "التدفقات النقدية",
    "cashflows.subtitle": "تتبع جميع توزيعات الأرباح والعوائد من استثماراتك",
    "cashflows.totalReceived": "إجمالي المستلم",
    "cashflows.expectedThisQuarter": "المتوقع هذا الربع",
    "cashflows.allCashflows": "جميع التدفقات",
    "cashflows.date": "التاريخ",
    "cashflows.investment": "الاستثمار",
    "cashflows.platform": "المنصة",
    "cashflows.amount": "المبلغ",
    "cashflows.status": "الحالة",
    "cashflows.type": "النوع",
    "cashflows.received": "مستلم",
    "cashflows.expected": "متوقع",
    "cashflows.upcoming": "قادم",
    "cashflows.profit": "ربح",
    "cashflows.principal": "رأس المال",
    "cashflows.noCashflows": "لا توجد تدفقات مسجلة بعد",
    "cashflows.inDays": "خلال {0} أيام",
    
    // Analytics
    "analytics.title": "التحليلات",
    "analytics.subtitle": "رؤى عميقة حول أداء محفظتك وتوقعاتها",
    "analytics.returns": "العوائد",
    "analytics.allocation": "التوزيع",
    "analytics.goals": "الأهداف",
    "analytics.monthlyReturnsTrend": "اتجاه العوائد الشهرية",
    "analytics.portfolioAllocation": "توزيع المحفظة حسب المنصة",
    "analytics.performanceVsTarget": "الأداء مقابل هدف 2040",
    
    // Timeline
    "timeline.title": "الخط الزمني",
    "timeline.subtitle": "سجل كامل لجميع الأنشطة الاستثمارية والمعاملات",
    "timeline.noActivity": "لا توجد أنشطة بعد",
    "timeline.noActivityDesc": "سيظهر خطك الزمني هنا عند إضافة استثمارات واستلام توزيعات",
    "timeline.investmentStarted": "بدء استثمار",
    "timeline.investmentMatured": "استحقاق استثمار",
    "timeline.profitReceived": "استلام توزيع أرباح",
    "timeline.newInvestment": "استثمار جديد في {0}",
    "timeline.matured": "{0} وصل للاستحقاق",
    "timeline.payment": "استلام دفعة {0}",
    "timeline.investment": "استثمار",
    "timeline.cashflow": "تدفق نقدي",
    "timeline.maturity": "استحقاق",
    
    // Alerts
    "alerts.title": "التنبيهات",
    "alerts.subtitle": "ابق على اطلاع بالإشعارات والأحداث المهمة",
    "alerts.unread": "{0} غير مقروء",
    "alerts.noAlertsYet": "لا توجد تنبيهات بعد",
    "alerts.noAlertsDesc": "ستتلقى إشعارات هنا للتوزيعات والاستحقاقات والأحداث المهمة",
    "alerts.markAsRead": "تحديد كمقروء",
    "alerts.distribution": "توزيع",
    "alerts.maturity": "استحقاق",
    "alerts.opportunity": "فرصة",
    "alerts.risk": "خطر",
    "alerts.success": "نجاح",
    "alerts.warning": "تحذير",
    "alerts.error": "خطأ",
    "alerts.info": "معلومات",
    
    // Reinvestment
    "reinvestment.title": "إعادة استثمار الأرباح",
    "reinvestment.description": "تتبع النقد المتاح وأعد استثمار أرباحك بشكل استراتيجي",
    "reinvestment.availableCash": "النقد المتاح",
    "reinvestment.fromDistributions": "من التوزيعات المستلمة",
    "reinvestment.totalInvested": "إجمالي المستثمر",
    "reinvestment.currentCapital": "رأس مال المحفظة الحالي",
    "reinvestment.receivedCount": "التوزيعات",
    "reinvestment.distributions": "توزيعات مستلمة",
    "reinvestment.opportunitiesTitle": "فرص إعادة الاستثمار",
    "reinvestment.opportunitiesDescription": "أفضل الاستثمارات النشطة مرتبة حسب العائد المتوقع",
    "reinvestment.noOpportunities": "لا توجد استثمارات نشطة متاحة لإعادة الاستثمار",
    "reinvestment.reinvest": "إعادة الاستثمار",
    "reinvestment.reinvestIn": "إعادة الاستثمار في",
    "reinvestment.reinvestDescription": "أدخل المبلغ الذي تريد إعادة استثماره في هذه الفرصة",
    "reinvestment.confirmReinvest": "تأكيد إعادة الاستثمار",
    "reinvestment.recentDistributions": "التوزيعات الأخيرة",
    "reinvestment.recentDistributionsDescription": "النقد المستلم من استثماراتك",
    "reinvestment.noDistributions": "لم يتم استلام توزيعات بعد",
    
    // Dialog
    "dialog.addInvestment": "إضافة استثمار جديد",
    "dialog.editInvestment": "تعديل الاستثمار",
    "dialog.addInvestmentDesc": "أدخل تفاصيل فرصتك الاستثمارية الجديدة",
    "dialog.editInvestmentDesc": "تحديث تفاصيل استثمارك",
    "dialog.platform": "المنصة",
    "dialog.selectPlatform": "اختر منصة",
    "dialog.investmentName": "اسم الاستثمار",
    "dialog.investmentNamePlaceholder": "مثال: صكوك 2025-أ",
    "dialog.amountSAR": "المبلغ (ريال سعودي)",
    "dialog.expectedIRR": "العائد المتوقع (%)",
    "dialog.expectedEndDate": "تاريخ الانتهاء المتوقع",
    "dialog.actualEndDate": "تاريخ الانتهاء الفعلي",
    "dialog.distributionFrequency": "تكرار التوزيع",
    "dialog.quarterly": "ربع سنوي",
    "dialog.semiAnnual": "نصف سنوي",
    "dialog.annual": "سنوي",
    "dialog.cancel": "إلغاء",
    "dialog.save": "حفظ",
    "dialog.saving": "جاري الحفظ...",
    "dialog.update": "تحديث الاستثمار",
    "dialog.add": "إضافة استثمار",
    "dialog.error": "خطأ",
    "dialog.success": "نجاح",
    "dialog.createError": "فشل إنشاء الاستثمار",
    "dialog.updateError": "فشل تحديث الاستثمار",
    
    // Export
    "export.report": "تصدير",
    "export.monthly": "تقرير شهري",
    "export.quarterly": "تقرير ربع سنوي",
    
    // View Mode
    "viewMode.pro": "الوضع الاحترافي",
    "viewMode.lite": "الوضع المبسط",
    
    // Settings
    "settings.title": "الإعدادات",
    "settings.description": "خصص تجربة مركزك الاستثماري",
    "settings.appearance": "المظهر",
    "settings.appearanceDesc": "خصص شكل ومظهر لوحة التحكم",
    "settings.theme": "المظهر",
    "settings.light": "فاتح",
    "settings.dark": "داكن",
    "settings.fontSize": "حجم الخط",
    "settings.small": "صغير",
    "settings.medium": "متوسط",
    "settings.large": "كبير",
    "settings.viewMode": "وضع العرض",
    "settings.proMode": "الوضع الاحترافي",
    "settings.liteMode": "الوضع المبسط",
    "settings.proModeDesc": "تحليلات تفصيلية كاملة، تفاصيل شاملة، ومخططات متقدمة",
    "settings.liteModeDesc": "واجهة مبسطة تعرض المقاييس الرئيسية والمعلومات الأساسية فقط",
    "settings.languageRegion": "اللغة والمنطقة",
    "settings.languageRegionDesc": "تكوين اللغة والتفضيلات الإقليمية",
    "settings.language": "اللغة",
    "settings.currency": "العملة",
    "settings.currencyNote": "حاليًا الريال السعودي فقط",
    "settings.investmentGoals": "الأهداف الاستثمارية",
    "settings.investmentGoalsDesc": "حدد أهدافك المالية وتفضيلاتك",
    "settings.targetCapital2040": "رأس المال المستهدف بحلول 2040",
    "settings.targetCapitalDesc": "هدفك المالي لرؤية 2040 (بالريال السعودي)",
    "settings.autoReinvest": "إعادة استثمار الأرباح تلقائيًا",
    "settings.autoReinvestDesc": "إعادة استثمار التوزيعات المستلمة تلقائيًا",
    "settings.platforms": "إدارة المنصات",
    "settings.platformsDesc": "إدارة منصات التمويل الجماعي الخاصة بك",
    "settings.existingPlatforms": "المنصات الحالية",
    "settings.addNewPlatform": "إضافة منصة جديدة",
    "settings.platformNamePlaceholder": "اسم المنصة",
    "settings.other": "أخرى",
    "settings.addPlatform": "إضافة منصة",
    "settings.saved": "تم حفظ الإعدادات",
    "settings.savedDesc": "تم تحديث تفضيلاتك بنجاح",
    "settings.saveError": "فشل حفظ الإعدادات",
    "settings.platformAdded": "تمت إضافة المنصة",
    "settings.platformAddedDesc": "تمت إضافة المنصة الجديدة بنجاح",
    "settings.platformAddError": "فشل إضافة المنصة",
    "settings.platformNameRequired": "اسم المنصة مطلوب",
    
    // Help & Guide
    "help.title": "المساعدة والدليل",
    "help.subtitle": "دليل شامل لاستخدام مركز A.Z المالي",
    "help.gettingStarted": "البدء",
    "help.gettingStartedDesc": "تعلم أساسيات مركز A.Z المالي وكيفية البدء في رحلتك الاستثمارية.",
    "help.addingInvestments": "إضافة الاستثمارات",
    "help.addingInvestmentsDesc": "انتقل إلى صفحة الاستثمارات وانقر على 'إضافة استثمار'. املأ التفاصيل بما في ذلك المنصة والمبلغ (استخدم زر +1000 ريال للراحة)، العائد المتوقع، درجة المخاطرة، والتواريخ. اختر الحالة: نشط (مستمر)، قيد الانتظار (لم يبدأ بعد)، أو مكتمل (منتهي).",
    "help.trackingCashflows": "تتبع التدفقات النقدية",
    "help.trackingCashflowsDesc": "راقب جميع توزيعات الأرباح وعوائد رأس المال في قسم التدفقات النقدية. قم بالتصفية حسب الحالة: مستلم (تم الدفع)، متوقع (مستحق قريبًا)، أو قادم (مجدول).",
    "help.reinvesting": "إعادة استثمار الأرباح",
    "help.reinvestingDesc": "استخدم صفحة إعادة الاستثمار لعرض النقد المتاح من التوزيعات. اختر استثمارًا عالي الأداء وانقر على 'إعادة الاستثمار' لمضاعفة عوائدك بشكل استراتيجي.",
    
    "help.features": "الميزات الرئيسية",
    "help.featuresDesc": "استكشف الميزات القوية لمركز A.Z المالي",
    "help.proLiteMode": "الوضع الاحترافي / المبسط",
    "help.proLiteModeDesc": "التبديل بين الوضع الاحترافي (تحليلات كاملة، تفاصيل شاملة، مخططات متقدمة) والوضع المبسط (عرض مبسط مع 4 مقاييس أساسية فقط). التبديل باستخدام الأيقونة في تذييل الشريط الجانبي.",
    "help.delayTracking": "تتبع التأخير والمتعثرة",
    "help.delayTrackingDesc": "للاستثمارات المكتملة، قم بتعيين تاريخ الانتهاء الفعلي. إذا تأخر عن تاريخ الانتهاء المتوقع، يحسب النظام أيام التأخير. التأخيرات ≥90 يومًا (3 أشهر) تُصنف تلقائيًا كـ 'متعثرة' مع شارة حمراء.",
    "help.quickInput": "الإدخال السريع (+1000 ريال)",
    "help.quickInputDesc": "عند إضافة الاستثمارات، استخدم زر +1000 ريال بجوار حقل المبلغ لإدخال البيانات بسرعة. كل نقرة تضيف 1000 ريال إلى القيمة الحالية.",
    "help.bilingualSupport": "الدعم ثنائي اللغة",
    "help.bilingualSupportDesc": "التبديل بين الإنجليزية والعربية (مع دعم RTL) باستخدام زر تبديل اللغة. يتكيف كل المحتوى، بما في ذلك التواريخ والأرقام، مع اختيارك للغة.",
    
    "help.metrics": "فهم المقاييس",
    "help.metricsDesc": "شرح مؤشرات الأداء الرئيسية",
    "help.totalCapital": "رأس المال الإجمالي",
    "help.totalCapitalDesc": "مجموع جميع مبالغ الاستثمار في محفظتك، بما في ذلك الاستثمارات النشطة والمعلقة والمكتملة.",
    "help.totalReturns": "إجمالي العوائد",
    "help.totalReturnsDesc": "مجموع جميع توزيعات الأرباح المستلمة وعوائد رأس المال من استثماراتك.",
    "help.averageIRR": "متوسط العائد الداخلي",
    "help.averageIRRDesc": "معدل العائد الداخلي - متوسط النسبة المئوية للعائد السنوي المتوقع عبر محفظتك، مرجح حسب مبلغ الاستثمار.",
    "help.progressTo2040": "التقدم نحو 2040",
    "help.progressTo2040Desc": "النسبة المئوية من رأس المال المستهدف في رؤية 2040 المحقق، محسوبة كـ (إجمالي العوائد / رأس المال المستهدف) × 100.",
    "help.availableCash": "النقد المتاح",
    "help.availableCashDesc": "النقد الجاهز لإعادة الاستثمار = الرصيد النقدي الإجمالي ناقص إعادة الاستثمارات النشطة/المعلقة. إعادة الاستثمارات المكتملة تعيد رأس مالها.",
    "help.distressedInvestments": "الاستثمارات المتعثرة",
    "help.distressedInvestmentsDesc": "الاستثمارات المكتملة المتأخرة بـ 3+ أشهر (≥90 يومًا). تحتاج هذه إلى اهتمام وقد تشير إلى مشاكل في المنصة.",
    
    "help.platforms": "المنصات المدعومة",
    "help.platformsDesc": "منصات التمويل الجماعي القائم على الديون المدمجة في النظام",
    "help.sukuk": "صكوك",
    "help.sukukDesc": "منصة استثمارية متوافقة مع الشريعة الإسلامية تقدم سندات وفرص تمويل متوافقة مع الشريعة.",
    "help.manfaa": "منفعة",
    "help.manfaaDesc": "منصة سعودية للتمويل الجماعي للاستثمارات القائمة على الديون مع ملفات مخاطر متنوعة.",
    "help.lendo": "ليندو",
    "help.lendoDesc": "منصة إقراض من نظير إلى نظير تربط المستثمرين بالمقترضين للاستثمارات ذات العائد الثابت.",
    "help.addCustomPlatform": "إضافة منصة مخصصة",
    "help.addCustomPlatformDesc": "انتقل إلى الإعدادات ← إدارة المنصات لإضافة منصات إضافية غير موجودة في القائمة الافتراضية.",
    
    "help.tips": "نصائح وأفضل الممارسات",
    "help.tipsDesc": "قم بتعظيم تجربتك مع هذه النصائح المفيدة",
    "help.tip1": "تحديث تواريخ الانتهاء الفعلية بانتظام",
    "help.tip1Desc": "للاستثمارات المكتملة، قم دائمًا بتعيين تاريخ الانتهاء الفعلي لتتبع التأخيرات وتحديد المنصات الإشكالية.",
    "help.tip2": "مراقبة الاستثمارات المتعثرة",
    "help.tip2Desc": "تحقق من شارات 'متعثرة' الحمراء بانتظام. فكر في تقليل التعرض للمنصات ذات التأخيرات المتكررة.",
    "help.tip3": "استخدام الوضع الاحترافي للتحليل",
    "help.tip3Desc": "قم بالتبديل إلى الوضع الاحترافي عند مراجعة أداء المحفظة للوصول إلى المخططات التفصيلية وتحليلات التدفق النقدي.",
    "help.tip4": "إعادة الاستثمار بشكل استراتيجي",
    "help.tip4Desc": "استخدم صفحة إعادة الاستثمار لتحديد الفرص ذات الأداء الأفضل المرتبة حسب العائد المتوقع قبل نشر النقد المتاح.",
    "help.tip5": "تحديد أهداف واقعية",
    "help.tip5Desc": "في الإعدادات، قم بتكوين رأس المال المستهدف لرؤية 2040 لتتبع التقدم نحو أهدافك المالية.",
    
    "help.settings": "الإعدادات والتخصيص",
    "help.settingsDesc": "خصص تجربة مركزك الاستثماري",
    "help.appearance": "إعدادات المظهر",
    "help.appearanceDesc": "خصص المظهر (فاتح/داكن)، حجم الخط (صغير/متوسط/كبير)، ووضع العرض. قم بالتبديل بين الوضع الاحترافي (تحليلات كاملة) والوضع المبسط (4 مقاييس أساسية) لتتناسب مع تفضيلك.",
    "help.languageSettings": "اللغة والمنطقة",
    "help.languageSettingsDesc": "التبديل بين الإنجليزية والعربية مع دعم RTL الكامل. العملة حاليًا هي الريال السعودي فقط. جميع التواريخ والأرقام والنصوص تتكيف مع اختيارك للغة.",
    "help.investmentGoalsSettings": "الأهداف الاستثمارية",
    "help.investmentGoalsSettingsDesc": "حدد رأس المال المستهدف لرؤية 2040 لتتبع التقدم المالي طويل الأجل. قم بتفعيل إعادة الاستثمار التلقائي لنشر التوزيعات المستلمة تلقائيًا في فرص جديدة.",
    "help.platformManagement": "إدارة المنصات",
    "help.platformManagementDesc": "عرض المنصات الحالية (صكوك، منفعة، ليندو) وإضافة منصات مخصصة. أدخل اسم المنصة واختر النوع (صكوك/منفعة/ليندو/أخرى) لتوسيع نطاق استثماراتك.",
  },
};

export function LanguageProvider({ children, defaultLanguage = "en" }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(
    () => (localStorage.getItem("language") as Language) || defaultLanguage
  );

  useEffect(() => {
    const root = document.documentElement;
    root.setAttribute("lang", language);
    root.setAttribute("dir", language === "ar" ? "rtl" : "ltr");
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageProviderContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageProviderContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageProviderContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
