import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

type LanguageProviderProps = {
  children: React.ReactNode;
  defaultLanguage?: Language;
};

type LanguageProviderState = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageProviderContext = createContext<LanguageProviderState | undefined>(undefined);

// Custom hook - must be defined before being exported to fix Fast Refresh
export function useLanguage() {
  const context = useContext(LanguageProviderContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Translation dictionaries
const translations = {
  en: {
    // Common
    "app.name": "A.Z Finance Hub",
    "app.subtitle": "Vision 2040",
    "app.copyright": "© 2025 A.Z Finance",
    "common.sar": "SAR",
    
    // Forecast
    "forecast.title": "Cashflow Forecast",
    "forecast.next": "Next",
    "forecast.months": "Months",
    "forecast.principal": "Principal",
    "forecast.profit": "Profit",
    "forecast.total": "Total",
    "forecast.period.month1": "1 Month",
    "forecast.period.month1Desc": "Next 30 days",
    "forecast.period.months3": "3 Months",
    "forecast.period.months3Desc": "Next Quarter",
    "forecast.period.months6": "6 Months",
    "forecast.period.months6Desc": "Next Half Year",
    "forecast.period.year1": "1 Year",
    "forecast.period.year1Desc": "Next 12 Months",
    "forecast.period.years2": "2 Years",
    "forecast.period.years2Desc": "Next 24 Months",
    "forecast.period.years5": "5 Years",
    "forecast.period.years5Desc": "Next 60 Months",
    "forecast.average": "Avg",
    "forecast.noData": "No forecast data available",
    "forecast.noDataDesc": "Add active investments to see cashflow projections",
    
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.investments": "Investments",
    "nav.cashflows": "Cashflows",
    "nav.cash": "Cash Management",
    "nav.analytics": "Analytics",
    "nav.reports": "Reports",
    "nav.aiInsights": "Smart Advisor",
    "nav.reinvestment": "Reinvestment",
    "nav.timeline": "Timeline",
    "nav.alerts": "Alerts",
    "nav.help": "Help & Guide",
    "nav.settings": "Settings",
    "nav.users": "Users",
    "nav.roles": "Roles",
    "nav.audit": "Audit Log",
    "nav.exportRequests": "Export Requests",
    "nav.viewRequests": "View Requests",
    
    // Admin
    "admin.users": "Users",
    "admin.roles": "Roles",
    "admin.exportRequests": "Export Requests",
    "admin.viewRequests": "View Requests",
    "admin.audit": "Audit Log",
    
    // Audit Log
    "audit.title": "Audit Log",
    "audit.subtitle": "Comprehensive record of all system activities and user actions",
    "audit.actor": "Actor",
    "audit.action": "Action",
    "audit.target": "Target",
    "audit.details": "Details",
    "audit.timestamp": "Timestamp",
    "audit.ipAddress": "IP Address",
    "audit.noLogs": "No audit logs found",
    "audit.noLogsDesc": "Activity records will appear here as users perform actions",
    "audit.filterByAction": "Filter by Action",
    "audit.filterByActor": "Filter by Actor",
    "audit.filterByTarget": "Filter by Target",
    "audit.allActions": "All Actions",
    "audit.allActors": "All Actors",
    "audit.allTargets": "All Targets",
    "audit.system": "System",
    "audit.clearFilters": "Clear Filters",
    "audit.exportLog": "Export Log",
    "audit.refreshLog": "Refresh",
    
    // Action Types
    "audit.action.view": "View",
    "audit.action.create": "Create",
    "audit.action.update": "Update",
    "audit.action.delete": "Delete",
    "audit.action.export": "Export",
    "audit.action.impersonate": "Impersonate",
    "audit.action.login": "Login",
    "audit.action.logout": "Logout",
    "audit.action.approve": "Approve",
    "audit.action.reject": "Reject",
    
    // Target Types
    "audit.target.investment": "Investment",
    "audit.target.user": "User",
    "audit.target.role": "Role",
    "audit.target.platform": "Platform",
    "audit.target.settings": "Settings",
    "audit.target.cashflow": "Cashflow",
    "audit.target.alert": "Alert",
    "audit.target.cash": "Cash",
    "audit.target.export": "Export Request",
    "audit.target.viewRequest": "View Request",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Welcome to your personal investment management hub",
    "dashboard.totalCapital": "Total Capital",
    "dashboard.totalReturns": "Total Returns",
    "dashboard.averageIrr": "Average IRR",
    "dashboard.progressTo2040": "Progress to 2040",
    "dashboard.vision2040Progress": "Vision 2040 Progress",
    "dashboard.vision2040Subtitle": "Track your journey towards financial independence",
    "dashboard.currentProgress": "Current Progress",
    "dashboard.expectedProgress": "Expected Progress",
    "dashboard.target2040": "Target 2040",
    "dashboard.by2040": "by 2040",
    "dashboard.requiredAnnualReturn": "Required Annual Return",
    "dashboard.toReachTarget": "to reach target",
    "dashboard.years": "years",
    "dashboard.aheadOfSchedule": "You are ahead of schedule!",
    "dashboard.behindSchedule": "Focus needed to reach the target",
    "dashboard.investmentStatus": "Investment Status",
    "dashboard.totalInvestments": "Total Investments",
    "dashboard.portfolioPerformance": "Portfolio Performance",
    "dashboard.upcomingCashflows": "Upcoming Cashflows",
    "dashboard.recentInvestments": "Recent Investments",
    "dashboard.noDataYet": "No data available yet",
    "dashboard.availableCash": "Available Cash",
    "dashboard.totalCashBalance": "Total Cash Balance",
    "dashboard.reinvestedAmount": "Reinvested",
    "dashboard.averageDuration": "Avg Duration",
    "dashboard.distressedCount": "Distressed",
    "dashboard.weightedAvgAPR": "Weighted Avg APR",
    "dashboard.nextPaymentExpected": "Next Payment",
    "dashboard.portfolioDiversification": "Diversification",
    "dashboard.reinvestmentRate": "Reinvestment Rate",
    "dashboard.days": "days",
    "dashboard.months": "months",
    "dashboard.investments": "investments",
    "dashboard.cashManagement": "Cash Management",
    "dashboard.additionalMetrics": "Additional Metrics",
    "dashboard.allPlatforms": "All Platforms",
    "dashboard.filterByPlatform": "Filter by Platform",
    "dashboard.statusBreakdown": "Investment Status Distribution",
    "dashboard.activeStatus": "Active",
    "dashboard.completedStatus": "Completed",
    "dashboard.delayedStatus": "Delayed",
    "dashboard.distressedStatus": "Distressed (3+ months)",
    "dashboard.capital": "Capital",
    "dashboard.returns": "Returns",
    "dashboard.irr": "IRR",
    "dashboard.duration": "Duration",
    "dashboard.activeInvestments": "Active Investments",
    "dashboard.completedInvestments": "Completed Investments",
    "dashboard.platformsOverview": "Platforms Overview",
    "dashboard.gridView": "Grid View",
    "dashboard.classicView": "Classic View",
    "dashboard.percentage": "%",
    "dashboard.count": "#",
    "dashboard.clickToToggle": "Click to toggle %/#",
    "dashboard.platformDistribution": "Platform Distribution",
    "dashboard.totalValue": "Total Value",
    "dashboard.noPlatformData": "No platform data",
    
    // Financial Metrics
    "metrics.activeAPR": "Active APR",
    "metrics.activeAPRSubtitle": "Weighted return for current positions",
    "metrics.historicalAPR": "Historical APR",
    "metrics.historicalAPRSubtitle": "All-time portfolio average",
    "metrics.portfolioROI": "Portfolio ROI",
    "metrics.expectedIRR": "Expected IRR",
    "metrics.currentROI": "Current ROI",
    
    // Status labels for charts
    "status.active": "Active",
    "status.completed": "Completed",
    "status.late": "Late",
    "status.defaulted": "Defaulted",
    
    // Platform
    "platform.notFound": "Platform not found",
    "platform.investments": "Investments",
    "platform.noInvestments": "No investments in this platform yet",
    
    // Common
    "common.back": "Back",
    "common.edit": "Edit",
    "common.delete": "Delete",
    
    // Investments
    "investments.title": "Investments",
    "investments.subtitle": "Manage your investment portfolio across multiple platforms",
    "investments.addInvestment": "Add Investment",
    "investments.noInvestmentsYet": "No investments yet",
    "investments.noInvestmentsDesc": "Start building your portfolio by adding your first investment opportunity",
    "investments.addFirstInvestment": "Add Your First Investment",
    "investments.editInvestment": "Edit Investment",
    "investments.amount": "Amount",
    "investments.irr": "Expected IRR",
    "investments.expectedIrr": "Expected IRR",
    "investments.roi": "ROI",
    "investments.currentROI": "Expected ROI",
    "investments.actualROI": "Actual ROI",
    "investments.risk": "Risk",
    "investments.startDate": "Start Date",
    "investments.endDate": "End Date",
    "investments.expectedEndDate": "Expected End Date",
    "investments.actualEndDate": "Actual End Date",
    "investments.status": "Status",
    "investments.riskScore": "Risk Score",
    "investments.daysRemaining": "days remaining",
    "investments.days": "days",
    "investments.delayed": "Delayed",
    "investments.distressed": "Distressed",
    "investments.active": "Active",
    "investments.completed": "Completed",
    "investments.late": "Late",
    "investments.defaulted": "Defaulted",
    "investments.pending": "Pending",
    "investments.confirmPayment": "Confirm Payment",
    "investments.duration": "Duration",
    "investments.avgPayment": "Avg Payment",
    "investments.deleteInvestment": "Delete Investment",
    "investments.deleteConfirm": "Are you sure you want to delete this investment?",
    "investments.deleteWarning": "This will permanently delete the investment and all related cashflows and alerts. This action cannot be undone.",
    "investments.expectedIRR": "Expected IRR",
    "investments.faceValue": "Face Value",
    "investments.totalReturns": "Total Returns",
    "investments.expectedProfit": "Expected Profit",
    "investments.months": "months",
    "investments.completePayment": "Complete Payment",
    
    // Cashflows
    "cashflows.title": "Cashflows",
    "cashflows.subtitle": "Track all profit distributions and returns from your investments",
    "cashflows.totalReceived": "Profits Received",
    "cashflows.expectedThisQuarter": "Expected This Quarter",
    "cashflows.allCashflows": "All Cashflows",
    "cashflows.allTransactions": "All Transactions",
    "cashflows.investmentCashflows": "Investment Cashflows",
    "cashflows.investmentDistribution": "Investment Distribution",
    "cashflows.noTransactions": "No transactions recorded yet",
    "cashflows.date": "Date",
    "cashflows.investment": "Investment",
    "cashflows.platform": "Platform",
    "cashflows.amount": "Amount",
    "cashflows.status": "Status",
    "cashflows.type": "Type",
    "cashflows.received": "Received",
    "cashflows.expected": "Expected",
    "cashflows.upcoming": "Upcoming",
    "cashflows.profit": "Profit",
    "cashflows.principal": "Principal",
    "cashflows.noCashflows": "No cashflows recorded yet",
    "cashflows.inDays": "in {0} days",
    
    // Analytics
    "analytics.title": "Analytics",
    "analytics.subtitle": "Deep insights into your portfolio performance and projections",
    "analytics.returns": "Returns",
    "analytics.allocation": "Allocation",
    "analytics.goals": "Goals",
    "analytics.monthlyReturnsTrend": "Monthly Returns Trend",
    "analytics.portfolioAllocation": "Portfolio Allocation by Platform",
    "analytics.performanceVsTarget": "Performance vs 2040 Target",
    
    // Smart Advisor (AI Insights)
    "aiInsights.title": "Smart Advisor",
    "aiInsights.subtitle": "Your intelligent investment companion powered by advanced AI",
    "aiInsights.refresh": "Refresh Analysis",
    "aiInsights.noData": "Unable to generate insights at this time",
    "aiInsights.tabs.overview": "Overview",
    "aiInsights.tabs.recommendations": "Recommendations",
    "aiInsights.tabs.riskAnalysis": "Risk Analysis",
    "aiInsights.tabs.forecast": "Forecast",
    "aiInsights.vision2040": "Vision 2040 Progress",
    "aiInsights.vision2040Description": "AI-powered forecast of your journey to financial independence",
    "aiInsights.currentProgress": "Current Progress",
    "aiInsights.predictedProgress": "Predicted by 2040",
    "aiInsights.suggestions": "Smart Suggestions",
    "aiInsights.marketInsights": "Market Insights",
    "aiInsights.recommendations": "Investment Recommendations",
    "aiInsights.recommendationsDescription": "Personalized recommendations tailored to your portfolio",
    "aiInsights.confidence": "Confidence",
    "aiInsights.potentialReturn": "Potential Return",
    "aiInsights.actionItems": "Action Items",
    "aiInsights.riskAnalysis": "Risk Analysis",
    "aiInsights.riskAnalysisDescription": "Comprehensive risk assessment of your portfolio",
    "aiInsights.overallRisk": "Overall Risk",
    "aiInsights.riskScore": "Risk Score",
    "aiInsights.riskFactors": "Risk Factors",
    "aiInsights.riskRecommendations": "Risk Mitigation Recommendations",
    "aiInsights.risk.low": "Low",
    "aiInsights.risk.medium": "Medium",
    "aiInsights.risk.high": "High",
    "aiInsights.cashflowForecast": "Cashflow Forecast",
    "aiInsights.cashflowForecastDescription": "AI-powered predictions of future cashflows",
    
    // Timeline
    "timeline.title": "Timeline",
    "timeline.subtitle": "Complete history of all investment activities and transactions",
    "timeline.noActivity": "No activity yet",
    "timeline.noActivityDesc": "Your investment timeline will appear here as you add investments and receive distributions",
    "timeline.investmentStarted": "Investment Started",
    "timeline.investmentMatured": "Investment Matured",
    "timeline.profitReceived": "Profit Distribution Received",
    "timeline.newInvestment": "New investment in {0}",
    "timeline.matured": "{0} reached maturity",
    "timeline.payment": "{0} payment received",
    "timeline.investment": "Investment",
    "timeline.cashflow": "Cashflow",
    "timeline.maturity": "Maturity",
    "timeline.cash_transaction": "Cash Transaction",
    "timeline.cashWithdrawn": "Cash withdrawn from portfolio",
    "timeline.cashDeposited": "Cash deposited to portfolio",
    
    // Alerts
    "alerts.title": "Alerts",
    "alerts.subtitle": "Stay updated with important notifications and events",
    "alerts.unread": "{0} unread",
    "alerts.noAlertsYet": "No alerts yet",
    "alerts.noAlertsDesc": "You'll receive notifications here for distributions, maturities, and important events",
    "alerts.markAsRead": "Mark as read",
    "alerts.distribution": "distribution",
    "alerts.maturity": "maturity",
    "alerts.opportunity": "opportunity",
    "alerts.risk": "risk",
    "alerts.success": "Success",
    "alerts.warning": "Warning",
    "alerts.error": "Error",
    "alerts.info": "Info",
    
    // Reinvestment
    "reinvestment.title": "Profit Reinvestment",
    "reinvestment.description": "Track available cash and reinvest your profits strategically",
    "reinvestment.availableCash": "Available Cash",
    "reinvestment.fromDistributions": "From received distributions",
    "reinvestment.totalInvested": "Total Invested",
    "reinvestment.currentCapital": "Current portfolio capital",
    "reinvestment.receivedCount": "Distributions",
    "reinvestment.distributions": "received distributions",
    "reinvestment.opportunitiesTitle": "Reinvestment Opportunities",
    "reinvestment.opportunitiesDescription": "Best performing active investments ranked by expected IRR",
    "reinvestment.noOpportunities": "No active investments available for reinvestment",
    "reinvestment.reinvest": "Reinvest",
    "reinvestment.reinvestIn": "Reinvest in",
    "reinvestment.reinvestDescription": "Enter the amount you want to reinvest into this opportunity",
    "reinvestment.confirmReinvest": "Confirm Reinvestment",
    "reinvestment.recentDistributions": "Recent Distributions",
    "reinvestment.recentDistributionsDescription": "Cash received from your investments",
    "reinvestment.noDistributions": "No distributions received yet",
    
    // Cash Management
    "cash.addCash": "Add Cash",
    "cash.withdrawCash": "Withdraw Cash",
    "cash.addCashTransaction": "Add Cash Transaction",
    "cash.withdrawCashTransaction": "Withdraw Cash",
    "cash.currentBalance": "Current Balance",
    "cash.amount": "Amount",
    "cash.transactionType": "Transaction Type",
    "cash.deposit": "Deposit",
    "cash.withdrawal": "Withdrawal",
    "cash.transfer": "Transfer",
    "cash.investment": "Investment",
    "cash.distribution": "Distribution",
    "cash.depositAdded": "Deposit Added",
    "cash.depositAddedDesc": "Cash deposit has been added successfully",
    "cash.withdrawalAdded": "Withdrawal Processed",
    "cash.withdrawalAddedDesc": "Cash withdrawal has been processed successfully",
    "cash.source": "Source",
    "cash.bank": "Bank",
    "cash.profit": "Profit",
    "cash.other": "Other",
    "cash.sourceTransfer": "Bank Transfer",
    "cash.sourceProfit": "Profit Distribution",
    "cash.sourceDeposit": "Direct Deposit",
    "cash.sourceInvestmentReturn": "Investment Return",
    "cash.date": "Date",
    "cash.notes": "Notes",
    "cash.notesPlaceholder": "Optional notes about this transaction",
    "cash.transactionAdded": "Transaction Added",
    "cash.transactionAddedDesc": "Cash transaction has been recorded successfully",
    "cash.failedToAdd": "Failed to add transaction",
    "cash.title": "Cash Management",
    "cash.cashTransactions": "Cash Transactions",
    "cash.availableBalance": "Available Balance",
    "cash.totalDeposits": "Total Deposits",
    "cash.totalWithdrawals": "Total Withdrawals",
    "cash.totalInvestments": "Total Investments",
    "cash.transactions": "Transactions",
    "cash.selectType": "Select Type",
    "cash.selectPeriod": "Select Period",
    "cash.noTransactions": "No transactions found",
    "cash.type": "Type",
    "cash.platform": "Platform",
    "cash.selectPlatform": "Select platform",
    "cash.noPlatform": "No specific platform",
    "cash.depositDescription": "Record a new deposit to your cash balance",
    "cash.withdrawalDescription": "Record a withdrawal from your cash balance",
    
    // Common
    "common.type": "Type",
    "common.filters": "Filters",
    "common.all": "All",
    "common.allTime": "All Time",
    "common.lastWeek": "Last Week",
    "common.lastMonth": "Last Month",
    "common.lastQuarter": "Last Quarter",
    "common.lastYear": "Last Year",
    "common.expand": "Expand",
    "common.compact": "Compact",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.saving": "Saving...",
    "common.error": "Error",
    
    // Dialog
    "dialog.addInvestment": "Add New Investment",
    "dialog.editInvestment": "Edit Investment",
    "dialog.addInvestmentDesc": "Enter the details of your new investment opportunity",
    "dialog.editInvestmentDesc": "Update the details of your investment",
    "dialog.platform": "Platform",
    "dialog.selectPlatform": "Select a platform",
    "dialog.investmentName": "Investment Name",
    "dialog.investmentNamePlaceholder": "e.g., Sukuk 2025-A",
    "dialog.amountSAR": "Amount (SAR)",
    "dialog.expectedIRR": "Expected IRR (%)",
    "dialog.expectedEndDate": "Expected End Date",
    "dialog.actualEndDate": "Actual End Date",
    "dialog.distributionFrequency": "Distribution Frequency",
    "dialog.monthly": "Monthly",
    "dialog.quarterly": "Quarterly",
    "dialog.semiAnnually": "Semi-Annually",
    "dialog.annually": "Annually",
    "dialog.atMaturity": "At Maturity (No Distributions)",
    "dialog.custom": "Custom Schedule",
    "dialog.customDistributions": "Custom Distributions",
    "dialog.customDistributionsDesc": "Define your own distribution schedule with specific dates and amounts",
    "dialog.addDistribution": "Add Distribution",
    "dialog.distributionDate": "Distribution Date",
    "dialog.distributionAmount": "Amount (SAR)",
    "dialog.distributionType": "Type",
    "dialog.distributionNotes": "Notes (optional)",
    "dialog.removeDistribution": "Remove",
    "dialog.totalCustomAmount": "Total Distributions Amount",
    "dialog.calculatedFields": "Calculated Investment Details",
    "dialog.totalExpectedReturn": "Total Expected Profit",
    "dialog.expectedProfit": "Expected Profit",
    "dialog.numberOfUnits": "Number of Sukuk Units",
    "dialog.paymentCount": "Number of Payments",
    "dialog.paymentValue": "Payment Value per Installment",
    "dialog.cancel": "Cancel",
    "dialog.save": "Save",
    "dialog.saving": "Saving...",
    "dialog.update": "Update Investment",
    "dialog.add": "Add Investment",
    "dialog.error": "Error",
    "dialog.success": "Success",
    "dialog.createError": "Failed to create investment",
    "dialog.updateError": "Failed to update investment",
    "dialog.confirmPayment": "Confirm Payment",
    "dialog.confirmPaymentDesc": "Mark this investment as fully paid and completed",
    "dialog.actualPaymentDate": "Actual Payment Date",
    "dialog.investmentCompleted": "Investment marked as completed successfully",
    "dialog.durationMode": "Duration Mode",
    "dialog.monthsMode": "Months",
    "dialog.datesMode": "Dates",
    "dialog.durationMonths": "Duration (Months)",
    "dialog.enterMonths": "Enter months",
    "dialog.calculateProfit": "Calculate",
    "dialog.recalculate": "Recalculate",
    "dialog.roi": "ROI",
    "dialog.over": "over",
    "dialog.months": "months",
    "dialog.calculatedAutomatically": "Calculated automatically",
    "dialog.manuallyEdited": "Manually edited - click Calculate to auto-fill",
    "dialog.faceValue": "Face Value",
    "dialog.faceValueDesc": "Principal investment amount",
    
    // Alerts
    "settings.alertSettings": "Alert Settings",
    "settings.alertSettingsDesc": "Manage automatic notifications and payment reminders",
    "settings.enableAlerts": "Enable Automatic Alerts",
    "settings.enableAlertsDesc": "Receive notifications for upcoming payments and deadlines",
    "settings.alertDaysBefore": "Days Before Due Date",
    "settings.alertDaysBeforeDesc": "Get notified this many days before a payment is due",
    "settings.latePaymentAlerts": "Late Payment Alerts",
    "settings.latePaymentAlertsDesc": "Get notifications for overdue payments",
    "settings.generateAlerts": "Generate Alerts Now",
    "settings.generatingAlerts": "Generating...",
    "settings.alertsGenerated": "Alerts Generated",
    "settings.alertsGeneratedDesc": "new alerts created",
    "settings.alertsGenerateError": "Failed to generate alerts",
    
    // Dashboard Customization
    "dashboard.customizeLayout": "Customize Layout",
    "dashboard.layoutSaved": "Layout Saved",
    "dashboard.layoutSavedDesc": "Your dashboard layout has been saved successfully",
    "dashboard.layoutSaveError": "Failed to save layout",
    "dashboard.resetLayout": "Reset Layout",
    "dashboard.widgetVisibility": "Widget Visibility",
    "dashboard.noPlatforms": "No platforms available",
    
    // Calculator
    "calculator.title": "Investment Goal Calculator",
    "calculator.description": "Calculate your future investment value based on deposits and returns",
    "calculator.initialAmount": "Initial Amount (SAR)",
    "calculator.monthlyDeposit": "Monthly Deposit (SAR)",
    "calculator.expectedIRR": "Expected Annual Return (%)",
    "calculator.durationYears": "Duration (Years)",
    "calculator.calculate": "Calculate Goal",
    "calculator.futureValue": "Future Value",
    "calculator.totalDeposits": "Total Deposits",
    "calculator.totalReturns": "Total Returns",
    "calculator.projectionChart": "Investment Projection",
    "calculator.years": "Years",
    "calculator.year": "Year",
    "calculator.deposits": "Deposits",
    
    // Vision 2040 Calculator
    "vision2040.title": "Vision 2040 Progress Calculator",
    "vision2040.subtitle": "Track your journey to financial independence",
    "vision2040.currentStatus": "Current Status",
    "vision2040.testScenario": "Test Scenario",
    "vision2040.whatIfScenario": "What-If Scenario",
    "vision2040.savedScenarios": "Saved Scenarios",
    "vision2040.saveScenario": "Save Scenario",
    "vision2040.loadScenario": "Load",
    "vision2040.deleteScenario": "Delete",
    "vision2040.scenarioName": "Scenario Name",
    "vision2040.scenarioNamePlaceholder": "Enter scenario name",
    "vision2040.maxScenariosReached": "Maximum 5 scenarios reached",
    "vision2040.noSavedScenarios": "No saved scenarios yet",
    "vision2040.noSavedScenariosDesc": "Save different planning scenarios to compare outcomes",
    "vision2040.scenarioSaved": "Scenario Saved",
    "vision2040.scenarioDeleted": "Scenario Deleted",
    "vision2040.scenarioLoaded": "Scenario Loaded",
    "vision2040.initialAmount": "Initial Amount",
    "vision2040.currentPortfolio": "Current Portfolio Value",
    "vision2040.monthlyContribution": "Monthly Contribution",
    "vision2040.expectedReturn": "Expected Annual Return",
    "vision2040.targetAmount": "Target Amount (2040)",
    "vision2040.yearsToGo": "Years to Go",
    "vision2040.currentProgress": "Current Progress",
    "vision2040.projectedValue": "Projected Value by 2040",
    "vision2040.requiredMonthly": "Required Monthly Contribution",
    "vision2040.requiredReturn": "Required Annual Return",
    "vision2040.completionDate": "Expected Completion Date",
    "vision2040.gapAnalysis": "Gap Analysis",
    "vision2040.monthlyGap": "Monthly Gap",
    "vision2040.toReachTarget": "to reach target",
    "vision2040.projectionTimeline": "Projection Timeline",
    "vision2040.currentPath": "Current Path",
    "vision2040.scenarioPath": "Scenario Path",
    "vision2040.targetGoal": "Target Goal",
    "vision2040.milestone": "Milestone",
    "vision2040.onTrack": "On Track",
    "vision2040.needsAttention": "Needs Attention",
    "vision2040.aheadOfSchedule": "Ahead of Schedule",
    "vision2040.behindSchedule": "Behind Schedule",
    "vision2040.adjustInputs": "Adjust your inputs to see different scenarios",
    "vision2040.successIndicator": "You're on track to reach your goal!",
    "vision2040.warningIndicator": "Increase contributions or returns to reach your goal",
    "vision2040.progressPercentage": "Progress to Target",
    "vision2040.timeRemaining": "Time Remaining",
    "vision2040.yearsLeft": "years left",
    "vision2040.compare": "Compare Scenarios",
    "vision2040.currentVsScenario": "Current vs Scenario",
    "vision2040.difference": "Difference",
    "vision2040.smartIndicators": "Smart Indicators",
    "vision2040.calculationInputs": "Calculation Inputs",
    "vision2040.currentBalance": "Current Balance",
    "vision2040.monthlyDeposit": "Monthly Deposit",
    "vision2040.target2040": "Target 2040",
    "vision2040.weighted": "weighted avg",
    "vision2040.targetPath": "Target Path",
    "vision2040.actualData": "Actual Data",
    "vision2040.generateTargets": "Generate Targets",
    "vision2040.progressChart": "Progress Chart",
    "vision2040.historicalData": "Historical Data",
    "vision2040.month": "Month",
    "vision2040.actualValue": "Actual Value",
    "vision2040.notes": "Notes",
    "vision2040.notesPlaceholder": "Add notes...",
    "vision2040.noData": "No data available",
    "vision2040.success": "Success",
    "vision2040.error": "Error",
    "vision2040.dataUpdated": "Data updated successfully",
    "vision2040.updateFailed": "Failed to update data",
    
    // Export
    "export.report": "Export",
    "export.monthly": "Monthly Report",
    "export.quarterly": "Quarterly Report",
    
    // View Mode
    "viewMode.pro": "Professional Mode",
    "viewMode.lite": "Lite Mode",
    
    // Settings
    "settings.title": "Settings",
    "settings.description": "Customize your investment hub experience",
    "settings.appearance": "Appearance",
    "settings.appearanceDesc": "Customize the look and feel of your dashboard",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.fontSize": "Font Size",
    "settings.small": "Small",
    "settings.medium": "Medium",
    "settings.large": "Large",
    "settings.viewMode": "View Mode",
    "settings.proMode": "Professional Mode",
    "settings.liteMode": "Lite Mode",
    "settings.proModeDesc": "Full detailed analytics, complete breakdowns, and advanced charts",
    "settings.liteModeDesc": "Simplified interface showing only main metrics and essential information",
    "settings.languageRegion": "Language & Region",
    "settings.languageRegionDesc": "Configure language and regional preferences",
    "settings.language": "Language",
    "settings.currency": "Currency",
    "settings.currencyNote": "Currently SAR (Saudi Riyal) only",
    "settings.investmentGoals": "Investment Goals",
    "settings.investmentGoalsDesc": "Set your financial targets and preferences",
    "settings.targetCapital2040": "Target Capital by 2040",
    "settings.targetCapitalDesc": "Your financial goal for Vision 2040 (in SAR)",
    "settings.autoReinvest": "Auto-Reinvest Profits",
    "settings.autoReinvestDesc": "Automatically reinvest received distributions",
    "settings.platforms": "Platform Management",
    "settings.platformsDesc": "Manage your crowdfunding platforms",
    "settings.existingPlatforms": "Existing Platforms",
    "settings.addNewPlatform": "Add New Platform",
    "settings.platformNamePlaceholder": "Platform name",
    "settings.other": "Other",
    "settings.addPlatform": "Add Platform",
    "settings.editPlatform": "Edit Platform",
    "settings.deletePlatform": "Delete Platform",
    "settings.editPlatformComingSoon": "Edit platform feature coming soon",
    "settings.deletePlatformConfirm": "Are you sure you want to delete this platform?",
    "settings.deletePlatformWarning": "This action cannot be undone. Make sure there are no investments linked to this platform.",
    "settings.platformDeleted": "Platform Deleted",
    "settings.platformDeletedDesc": "The platform has been removed successfully",
    "settings.platformDeleteError": "Failed to delete platform",
    "settings.platformHasInvestments": "Cannot delete platform: It has linked investments",
    "settings.saved": "Settings Saved",
    "settings.savedDesc": "Your preferences have been updated successfully",
    "settings.saveError": "Failed to save settings",
    "settings.platformAdded": "Platform Added",
    "settings.platformAddedDesc": "New platform has been added successfully",
    "settings.platformAddError": "Failed to add platform",
    "settings.platformNameRequired": "Platform name is required",
    "settings.security": "Security & Privacy",
    "settings.securityDesc": "Protect your financial data with biometric authentication",
    "settings.enableSecurity": "Enable App Security",
    "settings.enableSecurityDesc": "Require authentication when opening the app",
    "settings.setupPIN": "Setup PIN",
    "settings.setupPINDesc": "Set a 4-6 digit PIN for app access",
    "settings.enterPIN": "Enter new PIN (4-6 digits)",
    "settings.confirmPIN": "Confirm PIN",
    "settings.setPIN": "Set PIN",
    "settings.pinMismatch": "PINs do not match",
    "settings.pinTooShort": "PIN must be at least 4 digits",
    "settings.pinSet": "PIN Set Successfully",
    "settings.pinSetDesc": "Your security PIN has been configured",
    "settings.biometric": "Biometric Authentication",
    "settings.biometricDesc": "Use fingerprint or Face ID to unlock the app",
    "settings.enableBiometric": "Enable Biometric",
    "settings.registerBiometric": "Register Biometric",
    "settings.biometricNotSupported": "Biometric authentication not available on this device",
    "settings.biometricRegistered": "Biometric Registered",
    "settings.biometricRegisteredDesc": "You can now use biometric authentication",
    "settings.biometricRegisterError": "Failed to register biometric",
    
    // Checkpoints
    "checkpoints.title": "Portfolio Checkpoints",
    "checkpoints.titleDesc": "Save and restore complete portfolio snapshots",
    "checkpoints.saveCheckpoint": "Save Checkpoint",
    "checkpoints.restoreCheckpoint": "Restore Checkpoint",
    "checkpoints.deleteCheckpoint": "Delete Checkpoint",
    "checkpoints.checkpointName": "Checkpoint Name",
    "checkpoints.checkpointNamePlaceholder": "Enter checkpoint name",
    "checkpoints.createTitle": "Create Portfolio Checkpoint",
    "checkpoints.createDesc": "Save the current state of your entire portfolio",
    "checkpoints.restoreTitle": "Restore Portfolio",
    "checkpoints.restoreDesc": "This will replace ALL current data with the checkpoint data. This action cannot be undone.",
    "checkpoints.restoreWarning": "Are you sure you want to restore this checkpoint?",
    "checkpoints.deleteWarning": "Are you sure you want to delete this checkpoint?",
    "checkpoints.saved": "Checkpoint Saved",
    "checkpoints.savedDesc": "Portfolio snapshot created successfully",
    "checkpoints.saveError": "Failed to save checkpoint",
    "checkpoints.restored": "Portfolio Restored",
    "checkpoints.restoredDesc": "Portfolio data has been restored from checkpoint",
    "checkpoints.restoreError": "Failed to restore checkpoint",
    "checkpoints.deleted": "Checkpoint Deleted",
    "checkpoints.deletedDesc": "Checkpoint has been removed",
    "checkpoints.deleteError": "Failed to delete checkpoint",
    "checkpoints.noCheckpoints": "No Checkpoints",
    "checkpoints.noCheckpointsDesc": "Create your first checkpoint to save portfolio state",
    "checkpoints.created": "Created",
    "checkpoints.entities": "Entities",
    "checkpoints.investments": "Investments",
    "checkpoints.cashflows": "Cashflows",
    "checkpoints.size": "Size",
    
    // Lock Screen
    "lock.title": "A.Z Finance Hub",
    "lock.subtitle": "Vision 2040",
    "lock.welcome": "Welcome Back",
    "lock.enterPIN": "Enter your PIN to unlock",
    "lock.useBiometric": "Use Biometric",
    "lock.unlock": "Unlock",
    "lock.incorrectPIN": "Incorrect PIN",
    "lock.biometricFailed": "Biometric authentication failed",
    "lock.tryAgain": "Try again or use PIN",
    
    // Help & Guide
    "help.title": "Help & Guide",
    "help.subtitle": "Comprehensive guide to using A.Z Finance Hub",
    "help.gettingStarted": "Getting Started",
    "help.gettingStartedDesc": "Learn the basics of A.Z Finance Hub and how to get started with your investment journey.",
    "help.addingInvestments": "Adding Investments",
    "help.addingInvestmentsDesc": "Navigate to the Investments page and click 'Add Investment'. Fill in details including platform, amount (use +1000 SAR quick button for convenience), expected IRR, risk score, and dates. Select status: Active (ongoing), Pending (not yet started), or Completed (finished).",
    "help.trackingCashflows": "Tracking Cashflows",
    "help.trackingCashflowsDesc": "Monitor all profit distributions and principal returns in the Cashflows section. Filter by status: Received (already paid), Expected (due soon), or Upcoming (scheduled).",
    "help.reinvesting": "Reinvesting Profits",
    "help.reinvestingDesc": "Use the Reinvestment page to view available cash from distributions. Select a high-performing investment and click 'Reinvest' to compound your returns strategically.",
    
    "help.features": "Key Features",
    "help.featuresDesc": "Explore the powerful features of A.Z Finance Hub",
    "help.proLiteMode": "Pro / Lite Mode",
    "help.proLiteModeDesc": "Toggle between Professional Mode (full analytics, detailed breakdowns, advanced charts) and Lite Mode (simplified view with 4 core metrics only). Switch using the icon in the sidebar footer.",
    "help.delayTracking": "Delay & Distressed Tracking",
    "help.delayTrackingDesc": "For completed investments, set the Actual End Date. If delayed beyond Expected End Date, the system calculates delay days. Delays ≥90 days (3 months) automatically flag as 'Distressed' with a red badge.",
    "help.quickInput": "Quick Input (+1000 SAR)",
    "help.quickInputDesc": "When adding investments, use the +1000 SAR button next to the Amount field for fast data entry. Each click adds 1000 SAR to the current value.",
    "help.bilingualSupport": "Bilingual Support",
    "help.bilingualSupportDesc": "Switch between English and Arabic (with RTL support) using the language toggle button. All content, including dates and numbers, adapts to your language choice.",
    
    "help.metrics": "Understanding Metrics",
    "help.metricsDesc": "Key performance indicators explained",
    "help.totalCapital": "Total Capital",
    "help.totalCapitalDesc": "Sum of all investment amounts across your portfolio, including active, pending, and completed investments.",
    "help.totalReturns": "Total Returns",
    "help.totalReturnsDesc": "Sum of all received profit distributions and principal returns from your investments.",
    "help.averageIRR": "Average IRR",
    "help.averageIRRDesc": "Internal Rate of Return - the average expected annual return percentage across your portfolio, weighted by investment amount.",
    "help.progressTo2040": "Progress to 2040",
    "help.progressTo2040Desc": "Percentage of your Vision 2040 target capital achieved, calculated as (Total Returns / Target Capital) × 100.",
    "help.availableCash": "Available Cash",
    "help.availableCashDesc": "Cash ready for reinvestment = Total Cash Balance minus active/pending reinvestments. Completed reinvestments return their capital.",
    "help.distressedInvestments": "Distressed Investments",
    "help.distressedInvestmentsDesc": "Completed investments delayed by 3+ months (≥90 days). These require attention and may indicate platform issues.",
    
    "help.platforms": "Supported Platforms",
    "help.platformsDesc": "Crowdfunding debt platforms integrated into the system",
    "help.sukuk": "Sukuk",
    "help.sukukDesc": "Islamic compliant investment platform offering Sharia-compliant bonds and financing opportunities.",
    "help.manfaa": "Manfa'a",
    "help.manfaaDesc": "Saudi crowdfunding platform for debt-based investments with various risk profiles.",
    "help.lendo": "Lendo",
    "help.lendoDesc": "Peer-to-peer lending platform connecting investors with borrowers for fixed-return investments.",
    "help.addCustomPlatform": "Add Custom Platform",
    "help.addCustomPlatformDesc": "Go to Settings → Platform Management to add additional platforms not in the default list.",
    
    "help.tips": "Tips & Best Practices",
    "help.tipsDesc": "Maximize your experience with these helpful tips",
    "help.tip1": "Regularly Update Actual End Dates",
    "help.tip1Desc": "For completed investments, always set the Actual End Date to track delays and identify problematic platforms.",
    "help.tip2": "Monitor Distressed Investments",
    "help.tip2Desc": "Check for red 'Distressed' badges regularly. Consider reducing exposure to platforms with frequent delays.",
    "help.tip3": "Use Pro Mode for Analysis",
    "help.tip3Desc": "Switch to Professional Mode when reviewing portfolio performance to access detailed charts and cash flow analytics.",
    "help.tip4": "Reinvest Strategically",
    "help.tip4Desc": "Use the Reinvestment page to identify top-performing opportunities sorted by expected IRR before deploying available cash.",
    "help.tip5": "Set Realistic Goals",
    "help.tip5Desc": "In Settings, configure your Vision 2040 target capital to track progress toward your financial objectives.",
    
    "help.settings": "Settings & Customization",
    "help.settingsDesc": "Personalize your investment hub experience",
    "help.appearance": "Appearance Settings",
    "help.appearanceDesc": "Customize theme (Light/Dark), font size (Small/Medium/Large), and view mode. Toggle between Professional Mode (full analytics) and Lite Mode (4 core metrics) to match your preference.",
    "help.languageSettings": "Language & Region",
    "help.languageSettingsDesc": "Switch between English and Arabic with full RTL support. Currency is currently SAR (Saudi Riyal) only. All dates, numbers, and text adapt to your language choice.",
    "help.investmentGoalsSettings": "Investment Goals",
    "help.investmentGoalsSettingsDesc": "Set your Vision 2040 target capital to track long-term financial progress. Enable auto-reinvest to automatically deploy received distributions into new opportunities.",
    "help.platformManagement": "Platform Management",
    "help.platformManagementDesc": "View existing platforms (Sukuk, Manfa'a, Lendo) and add custom platforms. Enter platform name and select type (Sukuk/Manfa'a/Lendo/Other) to expand your investment universe.",
    
    // Auth & Login
    "login": "Login",
    "loginDescription": "Enter your credentials to access A.Z Finance Hub",
    "username": "Username",
    "password": "Password",
    "enterUsername": "Enter your username",
    "enterPassword": "Enter your password",
    "loggingIn": "Logging in...",
    "loginSuccess": "Login successful",
    "loginFailed": "Login Failed",
    "invalidCredentials": "Invalid username or password",
    "pleaseEnterCredentials": "Please enter your username and password",
    "error": "Error",
    "success": "Success",
    
    // User Management
    "userManagement": "User Management",
    "manageUsersAndRoles": "Manage users, roles, and permissions",
    "addUser": "Add User",
    "editUser": "Edit User",
    "allUsers": "All Users",
    "totalUsers": "Total Users",
    "noUsersFound": "No users found",
    "name": "Name",
    "fullName": "Full Name",
    "email": "Email",
    "phone": "Phone",
    "role": "Role",
    "status": "Status",
    "actions": "Actions",
    "active": "Active",
    "inactive": "Inactive",
    "noRole": "No Role",
    "selectRole": "Select a role",
    "newPassword": "New Password (leave blank to keep current)",
    "activeStatus": "Active Status",
    "activeStatusDescription": "User can login when active",
    "cancel": "Cancel",
    "save": "Save",
    "saving": "Saving...",
    "delete": "Delete",
    "deleting": "Deleting...",
    "confirmDelete": "Confirm Delete",
    "deleteUserConfirmation": "Are you sure you want to delete user",
    "userCreated": "User created successfully",
    "userUpdated": "User updated successfully",
    "userDeleted": "User deleted successfully",
    "userCreationFailed": "Failed to create user",
    "userUpdateFailed": "Failed to update user",
    "userDeletionFailed": "Failed to delete user",
    "impersonationStarted": "Now viewing as selected user",
    "impersonationFailed": "Failed to start impersonation",
    "impersonationActive": "You are impersonating another user",
    "endImpersonation": "End Impersonation",
    "impersonationEnded": "Impersonation ended successfully",
    "impersonationEndFailed": "Failed to end impersonation",
    "addUserDescription": "Create a new user account",
    "editUserDescription": "Update user details and permissions",
    "accessDenied": "Access Denied",
    "noPermissionToViewUsers": "You don't have permission to view this page",
    "loading": "Loading...",
    
    // Role Management
    "roleManagement": "Role Management",
    "manageRolesAndPermissions": "Manage system roles and their permissions",
    "addRole": "Add Role",
    "editRole": "Edit Role",
    "allRoles": "All Roles",
    "totalRoles": "Total Roles",
    "totalPermissions": "Total Permissions",
    "noRolesFound": "No roles found",
    "roleName": "Role Name",
    "displayNameEnglish": "Display Name (English)",
    "displayNameArabic": "Display Name (Arabic)",
    "description": "Description",
    "permissions": "Permissions",
    "permissionsCount": "permissions",
    "users": "Users",
    "viewAndManageSystemRoles": "View and manage system roles",
    "roleCreated": "Role created successfully",
    "roleUpdated": "Role updated successfully",
    "roleDeleted": "Role deleted successfully",
    "roleCreationFailed": "Failed to create role",
    "roleUpdateFailed": "Failed to update role",
    "roleDeletionFailed": "Failed to delete role",
    "deleteRoleConfirmation": "Are you sure you want to delete role",
    "addRoleDescription": "Create a new role with custom permissions",
    "editRoleDescription": "Update role details and permissions",
    "noPermissionToViewRoles": "You don't have permission to view this page",
    
    // Permission Categories
    "permissionCategory.user": "User Management",
    "permissionCategory.role": "Role Management",
    "permissionCategory.investment": "Investment Management",
    "permissionCategory.cashflow": "Cashflow Management",
    "permissionCategory.analytics": "Analytics",
    "permissionCategory.audit": "Audit",
    "permissionCategory.platform": "Platform",
    "permissionCategory.settings": "Settings",
    "permissionCategory.advanced": "Advanced Features",
    "permissionCategory.alerts": "Alerts",
    "permissionCategory.data": "Data Management",
    
    // Individual Permissions
    "permission.USER_MANAGE": "Manage Users",
    "permission.USER_CREATE": "Create Users",
    "permission.USER_EDIT": "Edit Users",
    "permission.USER_DELETE": "Delete Users",
    "permission.USER_VIEW_SENSITIVE": "View Sensitive User Data",
    "permission.ROLE_MANAGE": "Manage Roles",
    "permission.ROLE_CREATE": "Create Roles",
    "permission.ROLE_EDIT": "Edit Roles",
    "permission.ROLE_DELETE": "Delete Roles",
    "permission.INVESTMENT_VIEW": "View Investments",
    "permission.INVESTMENT_CREATE": "Create Investments",
    "permission.INVESTMENT_EDIT": "Edit Investments",
    "permission.INVESTMENT_DELETE": "Delete Investments",
    "permission.INVESTMENT_APPROVE": "Approve Investments",
    "permission.CASHFLOW_VIEW": "View Cashflows",
    "permission.CASHFLOW_CREATE": "Create Cashflows",
    "permission.CASHFLOW_EDIT": "Edit Cashflows",
    "permission.CASHFLOW_DELETE": "Delete Cashflows",
    "permission.ANALYTICS_VIEW": "View Analytics",
    "permission.ANALYTICS_EXPORT": "Export Analytics",
    "permission.AUDIT_VIEW": "View Audit Logs",
    "permission.AUDIT_EXPORT": "Export Audit Logs",
    "permission.PLATFORM_MANAGE": "Manage Platforms",
    "permission.SETTINGS_MANAGE": "Manage Settings",
    "permission.IMPERSONATE": "Impersonate Users",
    "permission.APPROVE_EXPORTS": "Approve Export Requests",
    "permission.APPROVE_VIEWS": "Approve View Requests",
    "permission.TEMPORARY_ROLE_ASSIGN": "Assign Temporary Roles",
    "permission.FIELD_MASKING_OVERRIDE": "Override Field Masking",
    "permission.ALERT_MANAGE": "Manage Alerts",
    "permission.DATA_EXPORT": "Export Data",
  },
  ar: {
    // Common
    "app.name": "مركز A.Z المالي",
    "app.subtitle": "رؤية 2040",
    "app.copyright": "© 2025 A.Z المالية",
    "common.sar": "ريال",
    
    // Forecast
    "forecast.title": "توقعات التدفقات النقدية",
    "forecast.next": "الـ",
    "forecast.months": "شهر القادمة",
    "forecast.principal": "رأس المال",
    "forecast.profit": "الأرباح",
    "forecast.total": "الإجمالي",
    "forecast.period.month1": "شهر واحد",
    "forecast.period.month1Desc": "الـ 30 يوم القادمة",
    "forecast.period.months3": "3 أشهر",
    "forecast.period.months3Desc": "الربع القادم",
    "forecast.period.months6": "6 أشهر",
    "forecast.period.months6Desc": "نصف السنة القادمة",
    "forecast.period.year1": "سنة واحدة",
    "forecast.period.year1Desc": "الـ 12 شهر القادمة",
    "forecast.period.years2": "سنتين",
    "forecast.period.years2Desc": "الـ 24 شهر القادمة",
    "forecast.period.years5": "5 سنوات",
    "forecast.period.years5Desc": "الـ 60 شهر القادمة",
    "forecast.average": "المتوسط",
    "forecast.noData": "لا توجد بيانات توقعات",
    "forecast.noDataDesc": "أضف استثمارات نشطة لرؤية توقعات التدفقات",
    
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.investments": "الاستثمارات",
    "nav.cashflows": "التدفقات النقدية",
    "nav.cash": "إدارة النقدية",
    "nav.analytics": "التحليلات",
    "nav.reports": "التقارير",
    "nav.reinvestment": "إعادة الاستثمار",
    "nav.timeline": "الخط الزمني",
    "nav.alerts": "التنبيهات",
    "nav.help": "المساعدة والدليل",
    "nav.settings": "الإعدادات",
    "nav.users": "المستخدمون",
    "nav.roles": "الأدوار",
    "nav.audit": "سجل التدقيق",
    "nav.exportRequests": "طلبات التصدير",
    "nav.viewRequests": "طلبات العرض",
    
    // Admin
    "admin.users": "المستخدمون",
    "admin.roles": "الأدوار",
    "admin.exportRequests": "طلبات التصدير",
    "admin.viewRequests": "طلبات العرض",
    "admin.audit": "سجل التدقيق",
    
    // Audit Log
    "audit.title": "سجل التدقيق",
    "audit.subtitle": "سجل شامل لجميع أنشطة النظام وإجراءات المستخدمين",
    "audit.actor": "المستخدم",
    "audit.action": "الإجراء",
    "audit.target": "الهدف",
    "audit.details": "التفاصيل",
    "audit.timestamp": "التوقيت",
    "audit.ipAddress": "عنوان IP",
    "audit.noLogs": "لا توجد سجلات تدقيق",
    "audit.noLogsDesc": "ستظهر سجلات النشاط هنا عند قيام المستخدمين بإجراءات",
    "audit.filterByAction": "تصفية حسب الإجراء",
    "audit.filterByActor": "تصفية حسب المستخدم",
    "audit.filterByTarget": "تصفية حسب الهدف",
    "audit.allActions": "جميع الإجراءات",
    "audit.allActors": "جميع المستخدمين",
    "audit.allTargets": "جميع الأهداف",
    "audit.system": "النظام",
    "audit.clearFilters": "مسح الفلاتر",
    "audit.exportLog": "تصدير السجل",
    "audit.refreshLog": "تحديث",
    
    // Action Types
    "audit.action.view": "عرض",
    "audit.action.create": "إنشاء",
    "audit.action.update": "تحديث",
    "audit.action.delete": "حذف",
    "audit.action.export": "تصدير",
    "audit.action.impersonate": "انتحال صفة",
    "audit.action.login": "تسجيل دخول",
    "audit.action.logout": "تسجيل خروج",
    "audit.action.approve": "موافقة",
    "audit.action.reject": "رفض",
    
    // Target Types
    "audit.target.investment": "استثمار",
    "audit.target.user": "مستخدم",
    "audit.target.role": "دور",
    "audit.target.platform": "منصة",
    "audit.target.settings": "إعدادات",
    "audit.target.cashflow": "تدفق نقدي",
    "audit.target.alert": "تنبيه",
    "audit.target.cash": "نقد",
    "audit.target.export": "طلب تصدير",
    "audit.target.viewRequest": "طلب عرض",
    
    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.subtitle": "مرحباً بك في مركز إدارة الاستثمارات الشخصي",
    "dashboard.totalCapital": "رأس المال الإجمالي",
    "dashboard.totalReturns": "إجمالي العوائد",
    "dashboard.averageIrr": "متوسط العائد الداخلي",
    "dashboard.progressTo2040": "التقدم نحو 2040",
    "dashboard.vision2040Progress": "التقدم نحو رؤية 2040",
    "dashboard.vision2040Subtitle": "تتبع رحلتك نحو الاستقلال المالي",
    "dashboard.currentProgress": "التقدم الحالي",
    "dashboard.expectedProgress": "التقدم المتوقع",
    "dashboard.target2040": "هدف 2040",
    "dashboard.by2040": "بحلول 2040",
    "dashboard.requiredAnnualReturn": "العائد السنوي المطلوب",
    "dashboard.toReachTarget": "للوصول للهدف",
    "dashboard.years": "سنوات",
    "dashboard.aheadOfSchedule": "أنت متقدم عن الجدول المحدد",
    "dashboard.behindSchedule": "تركيز مطلوب للوصول للهدف",
    "dashboard.investmentStatus": "حالة الاستثمارات",
    "dashboard.totalInvestments": "إجمالي الاستثمارات",
    "dashboard.portfolioPerformance": "أداء المحفظة",
    "dashboard.upcomingCashflows": "التدفقات القادمة",
    "dashboard.recentInvestments": "الاستثمارات الأخيرة",
    "dashboard.noDataYet": "لا توجد بيانات متاحة بعد",
    "dashboard.availableCash": "النقد المتاح",
    "dashboard.totalCashBalance": "الرصيد النقدي الإجمالي",
    "dashboard.reinvestedAmount": "المعاد استثماره",
    "dashboard.averageDuration": "متوسط المدة",
    "dashboard.distressedCount": "متعثرة",
    "dashboard.weightedAvgAPR": "متوسط APR المرجح",
    "dashboard.nextPaymentExpected": "الدفعة التالية",
    "dashboard.portfolioDiversification": "التنوع",
    "dashboard.reinvestmentRate": "نسبة إعادة الاستثمار",
    "dashboard.days": "يوم",
    "dashboard.months": "شهر",
    "dashboard.investments": "استثمارات",
    "dashboard.cashManagement": "إدارة النقد",
    "dashboard.additionalMetrics": "مقاييس إضافية",
    "dashboard.allPlatforms": "جميع المنصات",
    "dashboard.filterByPlatform": "تصفية حسب المنصة",
    "dashboard.statusBreakdown": "توزيع حالات الاستثمارات",
    "dashboard.activeStatus": "نشطة",
    "dashboard.completedStatus": "مكتملة",
    "dashboard.delayedStatus": "متأخرة",
    "dashboard.distressedStatus": "متعثرة (3+ أشهر)",
    "dashboard.capital": "رأس المال",
    "dashboard.returns": "العوائد",
    "dashboard.irr": "العائد الداخلي",
    "dashboard.duration": "المدة",
    "dashboard.activeInvestments": "الاستثمارات النشطة",
    "dashboard.completedInvestments": "الاستثمارات المكتملة",
    "dashboard.platformsOverview": "نظرة عامة على المنصات",
    "dashboard.gridView": "عرض الشبكة",
    "dashboard.classicView": "العرض التقليدي",
    "dashboard.percentage": "%",
    "dashboard.count": "#",
    "dashboard.clickToToggle": "اضغط للتبديل بين %/#",
    "dashboard.platformDistribution": "توزيع المنصات",
    "dashboard.totalValue": "القيمة الإجمالية",
    "dashboard.noPlatformData": "لا توجد بيانات للمنصات",
    
    // Financial Metrics
    "metrics.activeAPR": "العائد السنوي النشط",
    "metrics.activeAPRSubtitle": "متوسط العائد السنوي للفرص (القائمة والمتأخرة والمتعثرة)",
    "metrics.historicalAPR": "العائد السنوي التاريخي",
    "metrics.historicalAPRSubtitle": "متوسط العائد السنوي لجميع فرص المحفظة",
    "metrics.portfolioROI": "عائد الاستثمار",
    "metrics.expectedIRR": "العائد السنوي المتوقع",
    "metrics.currentROI": "العائد الحالي",
    
    // Status labels for charts
    "status.active": "نشطة",
    "status.completed": "مكتملة",
    "status.late": "متأخرة",
    "status.defaulted": "متعثرة",
    
    // Platform
    "platform.notFound": "المنصة غير موجودة",
    "platform.investments": "الاستثمارات",
    "platform.noInvestments": "لا توجد استثمارات في هذه المنصة بعد",
    
    // Common
    "common.back": "رجوع",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    
    // Investments
    "investments.title": "الاستثمارات",
    "investments.subtitle": "إدارة محفظة استثماراتك عبر منصات متعددة",
    "investments.addInvestment": "إضافة استثمار",
    "investments.noInvestmentsYet": "لا توجد استثمارات بعد",
    "investments.noInvestmentsDesc": "ابدأ ببناء محفظتك بإضافة أول فرصة استثمارية",
    "investments.addFirstInvestment": "أضف استثمارك الأول",
    "investments.editInvestment": "تعديل الاستثمار",
    "investments.amount": "المبلغ",
    "investments.irr": "العائد المتوقع",
    "investments.expectedIrr": "العائد المتوقع",
    "investments.roi": "العائد على الاستثمار",
    "investments.currentROI": "العائد المتوقع",
    "investments.actualROI": "العائد الفعلي",
    "investments.risk": "المخاطرة",
    "investments.startDate": "تاريخ البداية",
    "investments.endDate": "تاريخ النهاية",
    "investments.expectedEndDate": "تاريخ الانتهاء المتوقع",
    "investments.actualEndDate": "تاريخ الانتهاء الفعلي",
    "investments.status": "الحالة",
    "investments.riskScore": "درجة المخاطرة",
    "investments.daysRemaining": "أيام متبقية",
    "investments.days": "أيام",
    "investments.delayed": "متأخر",
    "investments.distressed": "متعثر",
    "investments.active": "نشط",
    "investments.completed": "مكتمل",
    "investments.late": "متأخر",
    "investments.defaulted": "متعثر",
    "investments.pending": "قيد الانتظار",
    "investments.confirmPayment": "تأكيد السداد",
    "investments.duration": "المدة",
    "investments.avgPayment": "متوسط الدفعة",
    "investments.deleteInvestment": "حذف الاستثمار",
    "investments.deleteConfirm": "هل أنت متأكد من حذف هذا الاستثمار؟",
    "investments.deleteWarning": "سيتم حذف الاستثمار ونهائياً وجميع التدفقات النقدية والتنبيهات المرتبطة به. لا يمكن التراجع عن هذا الإجراء.",
    "investments.expectedIRR": "معدل العائد المتوقع",
    "investments.faceValue": "القيمة الاسمية",
    "investments.totalReturns": "الأرباح المستلمة",
    "investments.expectedProfit": "الأرباح المتوقعة",
    "investments.months": "شهر",
    "investments.completePayment": "إتمام الدفعة",
    
    // Cashflows
    "cashflows.title": "التدفقات النقدية",
    "cashflows.subtitle": "تتبع جميع توزيعات الأرباح والعوائد من استثماراتك",
    "cashflows.totalReceived": "الأرباح المُستلمة",
    "cashflows.expectedThisQuarter": "المتوقع هذا الربع",
    "cashflows.allCashflows": "جميع التدفقات",
    "cashflows.allTransactions": "جميع المعاملات",
    "cashflows.investmentCashflows": "تدفقات الاستثمارات",
    "cashflows.investmentDistribution": "توزيعات استثمارية",
    "cashflows.noTransactions": "لا توجد معاملات مسجلة بعد",
    "cashflows.date": "التاريخ",
    "cashflows.investment": "الاستثمار",
    "cashflows.platform": "المنصة",
    "cashflows.amount": "المبلغ",
    "cashflows.status": "الحالة",
    "cashflows.type": "النوع",
    "cashflows.received": "مستلم",
    "cashflows.expected": "متوقع",
    "cashflows.upcoming": "قادم",
    "cashflows.profit": "ربح",
    "cashflows.principal": "رأس المال",
    "cashflows.noCashflows": "لا توجد تدفقات مسجلة بعد",
    "cashflows.inDays": "خلال {0} أيام",
    
    // Analytics
    "analytics.title": "التحليلات",
    "analytics.subtitle": "رؤى عميقة حول أداء محفظتك وتوقعاتها",
    "analytics.returns": "العوائد",
    "analytics.allocation": "التوزيع",
    "analytics.goals": "الأهداف",
    "analytics.monthlyReturnsTrend": "اتجاه العوائد الشهرية",
    "analytics.portfolioAllocation": "توزيع المحفظة حسب المنصة",
    "analytics.performanceVsTarget": "الأداء مقابل هدف 2040",
    
    // المستشار الذكي (Smart Advisor - AI Insights)
    "nav.aiInsights": "المستشار الذكي",
    "aiInsights.title": "المستشار الذكي",
    "aiInsights.subtitle": "رفيقك الاستثماري الذكي المدعوم بتقنية الذكاء الاصطناعي المتقدمة",
    "aiInsights.refresh": "تحديث التحليل",
    "aiInsights.noData": "تعذر إنشاء الرؤى في الوقت الحالي",
    "aiInsights.tabs.overview": "نظرة عامة",
    "aiInsights.tabs.recommendations": "التوصيات",
    "aiInsights.tabs.riskAnalysis": "تحليل المخاطر",
    "aiInsights.tabs.forecast": "التوقعات",
    "aiInsights.vision2040": "تقدم رؤية 2040",
    "aiInsights.vision2040Description": "توقعات مدعومة بالذكاء الاصطناعي لرحلتك نحو الاستقلال المالي",
    "aiInsights.currentProgress": "التقدم الحالي",
    "aiInsights.predictedProgress": "المتوقع بحلول 2040",
    "aiInsights.suggestions": "الاقتراحات الذكية",
    "aiInsights.marketInsights": "رؤى السوق",
    "aiInsights.recommendations": "التوصيات الاستثمارية",
    "aiInsights.recommendationsDescription": "توصيات مخصصة مصممة خصيصاً لمحفظتك",
    "aiInsights.confidence": "الموثوقية",
    "aiInsights.potentialReturn": "العائد المحتمل",
    "aiInsights.actionItems": "خطوات العمل",
    "aiInsights.riskAnalysis": "تحليل المخاطر",
    "aiInsights.riskAnalysisDescription": "تقييم شامل للمخاطر في محفظتك",
    "aiInsights.overallRisk": "المخاطرة الإجمالية",
    "aiInsights.riskScore": "درجة المخاطرة",
    "aiInsights.riskFactors": "عوامل المخاطرة",
    "aiInsights.riskRecommendations": "توصيات للحد من المخاطر",
    "aiInsights.risk.low": "منخفضة",
    "aiInsights.risk.medium": "متوسطة",
    "aiInsights.risk.high": "عالية",
    "aiInsights.cashflowForecast": "توقع التدفقات النقدية",
    "aiInsights.cashflowForecastDescription": "تنبؤات مدعومة بالذكاء الاصطناعي للتدفقات المستقبلية",
    
    // Timeline
    "timeline.title": "الخط الزمني",
    "timeline.subtitle": "سجل كامل لجميع الأنشطة الاستثمارية والمعاملات",
    "timeline.noActivity": "لا توجد أنشطة بعد",
    "timeline.noActivityDesc": "سيظهر خطك الزمني هنا عند إضافة استثمارات واستلام توزيعات",
    "timeline.investmentStarted": "بدء استثمار",
    "timeline.investmentMatured": "استحقاق استثمار",
    "timeline.profitReceived": "استلام توزيع أرباح",
    "timeline.newInvestment": "استثمار جديد في {0}",
    "timeline.matured": "{0} وصل للاستحقاق",
    "timeline.payment": "استلام دفعة {0}",
    "timeline.investment": "استثمار",
    "timeline.cashflow": "تدفق نقدي",
    "timeline.maturity": "استحقاق",
    "timeline.cash_transaction": "معاملة نقدية",
    "timeline.cashWithdrawn": "سحب نقدي من المحفظة",
    "timeline.cashDeposited": "إيداع نقدي في المحفظة",
    
    // Alerts
    "alerts.title": "التنبيهات",
    "alerts.subtitle": "ابق على اطلاع بالإشعارات والأحداث المهمة",
    "alerts.unread": "{0} غير مقروء",
    "alerts.noAlertsYet": "لا توجد تنبيهات بعد",
    "alerts.noAlertsDesc": "ستتلقى إشعارات هنا للتوزيعات والاستحقاقات والأحداث المهمة",
    "alerts.markAsRead": "تحديد كمقروء",
    "alerts.distribution": "توزيع",
    "alerts.maturity": "استحقاق",
    "alerts.opportunity": "فرصة",
    "alerts.risk": "خطر",
    "alerts.success": "نجاح",
    "alerts.warning": "تحذير",
    "alerts.error": "خطأ",
    "alerts.info": "معلومات",
    
    // Reinvestment
    "reinvestment.title": "إعادة استثمار الأرباح",
    "reinvestment.description": "تتبع النقد المتاح وأعد استثمار أرباحك بشكل استراتيجي",
    "reinvestment.availableCash": "النقد المتاح",
    "reinvestment.fromDistributions": "من التوزيعات المستلمة",
    "reinvestment.totalInvested": "إجمالي المستثمر",
    "reinvestment.currentCapital": "رأس مال المحفظة الحالي",
    "reinvestment.receivedCount": "التوزيعات",
    "reinvestment.distributions": "توزيعات مستلمة",
    "reinvestment.opportunitiesTitle": "فرص إعادة الاستثمار",
    "reinvestment.opportunitiesDescription": "أفضل الاستثمارات النشطة مرتبة حسب العائد المتوقع",
    "reinvestment.noOpportunities": "لا توجد استثمارات نشطة متاحة لإعادة الاستثمار",
    "reinvestment.reinvest": "إعادة الاستثمار",
    "reinvestment.reinvestIn": "إعادة الاستثمار في",
    "reinvestment.reinvestDescription": "أدخل المبلغ الذي تريد إعادة استثماره في هذه الفرصة",
    "reinvestment.confirmReinvest": "تأكيد إعادة الاستثمار",
    "reinvestment.recentDistributions": "التوزيعات الأخيرة",
    "reinvestment.recentDistributionsDescription": "النقد المستلم من استثماراتك",
    "reinvestment.noDistributions": "لم يتم استلام توزيعات بعد",
    
    // Cash Management
    "cash.addCash": "إضافة كاش",
    "cash.withdrawCash": "سحب كاش",
    "cash.addCashTransaction": "إضافة معاملة نقدية",
    "cash.withdrawCashTransaction": "سحب نقد",
    "cash.currentBalance": "الرصيد الحالي",
    "cash.amount": "المبلغ",
    "cash.transactionType": "نوع المعاملة",
    "cash.deposit": "إيداع",
    "cash.withdrawal": "سحب",
    "cash.transfer": "تحويل",
    "cash.investment": "استثمار",
    "cash.distribution": "توزيع",
    "cash.depositAdded": "تمت الإضافة",
    "cash.depositAddedDesc": "تم إيداع المبلغ بنجاح",
    "cash.withdrawalAdded": "تم السحب",
    "cash.withdrawalAddedDesc": "تم سحب المبلغ بنجاح",
    "cash.source": "المصدر",
    "cash.bank": "بنك",
    "cash.profit": "أرباح",
    "cash.other": "أخرى",
    "cash.sourceTransfer": "تحويل بنكي",
    "cash.sourceProfit": "توزيع أرباح",
    "cash.sourceDeposit": "إيداع مباشر",
    "cash.sourceInvestmentReturn": "عائد استثمار",
    "cash.date": "التاريخ",
    "cash.notes": "ملاحظات",
    "cash.notesPlaceholder": "ملاحظات اختيارية عن هذه المعاملة",
    "cash.transactionAdded": "تمت إضافة المعاملة",
    "cash.transactionAddedDesc": "تم تسجيل المعاملة النقدية بنجاح",
    "cash.failedToAdd": "فشل إضافة المعاملة",
    "cash.title": "إدارة النقدية",
    "cash.cashTransactions": "المعاملات النقدية",
    "cash.availableBalance": "الرصيد المتاح",
    "cash.totalDeposits": "إجمالي الإيداعات",
    "cash.totalWithdrawals": "إجمالي السحوبات",
    "cash.totalInvestments": "إجمالي الاستثمارات",
    "cash.transactions": "المعاملات",
    "cash.selectType": "اختر النوع",
    "cash.selectPeriod": "اختر الفترة",
    "cash.noTransactions": "لا توجد معاملات",
    "cash.type": "النوع",
    "cash.platform": "المنصة",
    "cash.selectPlatform": "اختر المنصة",
    "cash.noPlatform": "بدون منصة محددة",
    "cash.depositDescription": "تسجيل إيداع جديد للرصيد النقدي",
    "cash.withdrawalDescription": "تسجيل سحب من الرصيد النقدي",
    
    // Common
    "common.type": "النوع",
    "common.filters": "الفلاتر",
    "common.all": "الكل",
    "common.allTime": "كل الأوقات",
    "common.lastWeek": "الأسبوع الماضي",
    "common.lastMonth": "الشهر الماضي",
    "common.lastQuarter": "الربع الماضي",
    "common.lastYear": "السنة الماضية",
    "common.expand": "توسيع",
    "common.compact": "مضغوط",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.saving": "جاري الحفظ...",
    "common.error": "خطأ",
    
    // Dialog
    "dialog.addInvestment": "إضافة استثمار جديد",
    "dialog.editInvestment": "تعديل الاستثمار",
    "dialog.addInvestmentDesc": "أدخل تفاصيل فرصتك الاستثمارية الجديدة",
    "dialog.editInvestmentDesc": "تحديث تفاصيل استثمارك",
    "dialog.platform": "المنصة",
    "dialog.selectPlatform": "اختر منصة",
    "dialog.investmentName": "اسم الاستثمار",
    "dialog.investmentNamePlaceholder": "مثال: صكوك 2025-أ",
    "dialog.amountSAR": "المبلغ (ريال سعودي)",
    "dialog.expectedIRR": "العائد المتوقع (%)",
    "dialog.expectedEndDate": "تاريخ الانتهاء المتوقع",
    "dialog.actualEndDate": "تاريخ الانتهاء الفعلي",
    "dialog.distributionFrequency": "تكرار التوزيع",
    "dialog.monthly": "شهري",
    "dialog.quarterly": "ربع سنوي",
    "dialog.semiAnnually": "نصف سنوي",
    "dialog.annually": "سنوي",
    "dialog.atMaturity": "عند الاستحقاق (بدون توزيعات)",
    "dialog.custom": "جدول مخصص",
    "dialog.customDistributions": "التوزيعات المخصصة",
    "dialog.customDistributionsDesc": "حدد جدول التوزيعات الخاص بك بتواريخ وقيم محددة",
    "dialog.addDistribution": "إضافة توزيع",
    "dialog.distributionDate": "تاريخ التوزيع",
    "dialog.distributionAmount": "المبلغ (ريال)",
    "dialog.distributionType": "النوع",
    "dialog.distributionNotes": "ملاحظات (اختياري)",
    "dialog.removeDistribution": "إزالة",
    "dialog.totalCustomAmount": "إجمالي قيمة التوزيعات",
    "dialog.calculatedFields": "التفاصيل المحسوبة",
    "dialog.totalExpectedReturn": "إجمالي الأرباح المتوقعة",
    "dialog.expectedProfit": "الأرباح المتوقعة",
    "dialog.numberOfUnits": "عدد الصكوك",
    "dialog.paymentCount": "عدد الدفعات",
    "dialog.paymentValue": "قيمة كل دفعة",
    "dialog.cancel": "إلغاء",
    "dialog.save": "حفظ",
    "dialog.saving": "جاري الحفظ...",
    "dialog.update": "تحديث الاستثمار",
    "dialog.add": "إضافة استثمار",
    "dialog.error": "خطأ",
    "dialog.success": "نجاح",
    "dialog.createError": "فشل إنشاء الاستثمار",
    "dialog.updateError": "فشل تحديث الاستثمار",
    "dialog.confirmPayment": "تأكيد السداد",
    "dialog.confirmPaymentDesc": "وضع علامة على هذا الاستثمار كمسدد بالكامل ومكتمل",
    "dialog.actualPaymentDate": "تاريخ السداد الفعلي",
    "dialog.investmentCompleted": "تم وضع علامة على الاستثمار كمكتمل بنجاح",
    "dialog.durationMode": "نمط المدة",
    "dialog.monthsMode": "الأشهر",
    "dialog.datesMode": "التواريخ",
    "dialog.durationMonths": "المدة (بالأشهر)",
    "dialog.enterMonths": "أدخل الأشهر",
    "dialog.calculateProfit": "احسب",
    "dialog.recalculate": "إعادة الحساب",
    "dialog.roi": "العائد على الاستثمار",
    "dialog.over": "على مدى",
    "dialog.months": "شهر",
    "dialog.calculatedAutomatically": "محسوب تلقائياً",
    "dialog.manuallyEdited": "تم التعديل يدوياً - انقر احسب للملء التلقائي",
    "dialog.faceValue": "القيمة الاسمية",
    "dialog.faceValueDesc": "مبلغ الاستثمار الأساسي",
    
    // Alerts
    "settings.alertSettings": "إعدادات التنبيهات",
    "settings.alertSettingsDesc": "إدارة الإشعارات التلقائية وتذكيرات الدفع",
    "settings.enableAlerts": "تفعيل التنبيهات التلقائية",
    "settings.enableAlertsDesc": "استلام إشعارات للدفعات القادمة والمواعيد النهائية",
    "settings.alertDaysBefore": "الأيام قبل موعد الاستحقاق",
    "settings.alertDaysBeforeDesc": "استلام إشعار قبل موعد الدفع بهذا العدد من الأيام",
    "settings.latePaymentAlerts": "تنبيهات التأخر في السداد",
    "settings.latePaymentAlertsDesc": "استلام إشعارات للدفعات المتأخرة",
    "settings.generateAlerts": "إنشاء التنبيهات الآن",
    "settings.generatingAlerts": "جاري الإنشاء...",
    "settings.alertsGenerated": "تم إنشاء التنبيهات",
    "settings.alertsGeneratedDesc": "تنبيهات جديدة تم إنشاؤها",
    "settings.alertsGenerateError": "فشل إنشاء التنبيهات",
    
    // Dashboard Customization
    "dashboard.customizeLayout": "تخصيص التخطيط",
    "dashboard.layoutSaved": "تم حفظ التخطيط",
    "dashboard.layoutSavedDesc": "تم حفظ تخطيط لوحة التحكم بنجاح",
    "dashboard.layoutSaveError": "فشل حفظ التخطيط",
    "dashboard.resetLayout": "إعادة تعيين التخطيط",
    "dashboard.widgetVisibility": "رؤية الويدجت",
    "dashboard.noPlatforms": "لا توجد منصات متاحة",
    
    // Calculator
    "calculator.title": "حاسبة الهدف الاستثماري",
    "calculator.description": "حاسبة استثمارية لتحقيق طموحاتك",
    "calculator.initialAmount": "المبلغ الابتدائي (ريال)",
    "calculator.monthlyDeposit": "الإيداع الشهري (ريال)",
    "calculator.expectedIRR": "العائد السنوي المتوقع (%)",
    "calculator.durationYears": "المدة (سنوات)",
    "calculator.calculate": "احسب الهدف",
    "calculator.futureValue": "القيمة المستقبلية",
    "calculator.totalDeposits": "إجمالي الإيداعات",
    "calculator.totalReturns": "إجمالي العوائد",
    "calculator.projectionChart": "توقعات الاستثمار",
    "calculator.years": "السنوات",
    "calculator.year": "السنة",
    "calculator.deposits": "الإيداعات",
    
    // Vision 2040 Calculator
    "vision2040.title": "حاسبة التقدم نحو رؤية 2040",
    "vision2040.subtitle": "تتبع رحلتك نحو الاستقلال المالي",
    "vision2040.currentStatus": "الوضع الحالي",
    "vision2040.testScenario": "سيناريو تجريبي",
    "vision2040.whatIfScenario": "سيناريو ماذا لو",
    "vision2040.savedScenarios": "السيناريوهات المحفوظة",
    "vision2040.saveScenario": "حفظ السيناريو",
    "vision2040.loadScenario": "تحميل",
    "vision2040.deleteScenario": "حذف",
    "vision2040.scenarioName": "اسم السيناريو",
    "vision2040.scenarioNamePlaceholder": "أدخل اسم السيناريو",
    "vision2040.maxScenariosReached": "تم الوصول للحد الأقصى 5 سيناريوهات",
    "vision2040.noSavedScenarios": "لا توجد سيناريوهات محفوظة",
    "vision2040.noSavedScenariosDesc": "احفظ سيناريوهات مختلفة لمقارنة النتائج",
    "vision2040.scenarioSaved": "تم حفظ السيناريو",
    "vision2040.scenarioDeleted": "تم حذف السيناريو",
    "vision2040.scenarioLoaded": "تم تحميل السيناريو",
    "vision2040.initialAmount": "المبلغ الأولي",
    "vision2040.currentPortfolio": "قيمة المحفظة الحالية",
    "vision2040.monthlyContribution": "الإيداع الشهري",
    "vision2040.expectedReturn": "العائد السنوي المتوقع",
    "vision2040.targetAmount": "المبلغ المستهدف (2040)",
    "vision2040.yearsToGo": "سنوات متبقية",
    "vision2040.currentProgress": "التقدم الحالي",
    "vision2040.projectedValue": "القيمة المتوقعة بحلول 2040",
    "vision2040.requiredMonthly": "الإيداع الشهري المطلوب",
    "vision2040.requiredReturn": "العائد السنوي المطلوب",
    "vision2040.completionDate": "تاريخ الإنجاز المتوقع",
    "vision2040.gapAnalysis": "تحليل الفجوة",
    "vision2040.monthlyGap": "الفجوة الشهرية",
    "vision2040.toReachTarget": "للوصول للهدف",
    "vision2040.projectionTimeline": "الخط الزمني للتوقعات",
    "vision2040.currentPath": "المسار الحالي",
    "vision2040.scenarioPath": "مسار السيناريو",
    "vision2040.targetGoal": "الهدف المستهدف",
    "vision2040.milestone": "معلم رئيسي",
    "vision2040.onTrack": "على المسار الصحيح",
    "vision2040.needsAttention": "يحتاج اهتمام",
    "vision2040.aheadOfSchedule": "متقدم عن الجدول",
    "vision2040.behindSchedule": "متأخر عن الجدول",
    "vision2040.adjustInputs": "عدّل المدخلات لرؤية سيناريوهات مختلفة",
    "vision2040.successIndicator": "أنت على المسار الصحيح لتحقيق هدفك!",
    "vision2040.warningIndicator": "زد الإيداعات أو العوائد للوصول لهدفك",
    "vision2040.progressPercentage": "نسبة التقدم للهدف",
    "vision2040.timeRemaining": "الوقت المتبقي",
    "vision2040.yearsLeft": "سنة متبقية",
    "vision2040.compare": "مقارنة السيناريوهات",
    "vision2040.currentVsScenario": "الحالي مقابل السيناريو",
    "vision2040.difference": "الفرق",
    "vision2040.smartIndicators": "مؤشرات ذكية",
    "vision2040.calculationInputs": "مدخلات الحساب",
    "vision2040.currentBalance": "الرصيد الحالي",
    "vision2040.monthlyDeposit": "الإيداع الشهري",
    "vision2040.target2040": "الهدف 2040",
    "vision2040.weighted": "متوسط موزون",
    "vision2040.targetPath": "المسار المستهدف",
    "vision2040.actualData": "البيانات الفعلية",
    "vision2040.generateTargets": "حساب الأهداف",
    "vision2040.progressChart": "الرسم البياني",
    "vision2040.historicalData": "البيانات التاريخية",
    "vision2040.month": "الشهر",
    "vision2040.actualValue": "القيمة الفعلية",
    "vision2040.notes": "ملاحظات",
    "vision2040.notesPlaceholder": "أضف ملاحظات...",
    "vision2040.noData": "لا توجد بيانات",
    "vision2040.success": "نجح",
    "vision2040.error": "خطأ",
    "vision2040.dataUpdated": "تم تحديث البيانات بنجاح",
    "vision2040.updateFailed": "فشل تحديث البيانات",
    
    // Export
    "export.report": "تصدير",
    "export.monthly": "تقرير شهري",
    "export.quarterly": "تقرير ربع سنوي",
    
    // View Mode
    "viewMode.pro": "الوضع الاحترافي",
    "viewMode.lite": "الوضع المبسط",
    
    // Settings
    "settings.title": "الإعدادات",
    "settings.description": "خصص تجربة مركزك الاستثماري",
    "settings.appearance": "المظهر",
    "settings.appearanceDesc": "خصص شكل ومظهر لوحة التحكم",
    "settings.theme": "المظهر",
    "settings.light": "فاتح",
    "settings.dark": "داكن",
    "settings.fontSize": "حجم الخط",
    "settings.small": "صغير",
    "settings.medium": "متوسط",
    "settings.large": "كبير",
    "settings.viewMode": "وضع العرض",
    "settings.proMode": "الوضع الاحترافي",
    "settings.liteMode": "الوضع المبسط",
    "settings.proModeDesc": "تحليلات تفصيلية كاملة، تفاصيل شاملة، ومخططات متقدمة",
    "settings.liteModeDesc": "واجهة مبسطة تعرض المقاييس الرئيسية والمعلومات الأساسية فقط",
    "settings.languageRegion": "اللغة والمنطقة",
    "settings.languageRegionDesc": "تكوين اللغة والتفضيلات الإقليمية",
    "settings.language": "اللغة",
    "settings.currency": "العملة",
    "settings.currencyNote": "حاليًا الريال السعودي فقط",
    "settings.investmentGoals": "الأهداف الاستثمارية",
    "settings.investmentGoalsDesc": "حدد أهدافك المالية وتفضيلاتك",
    "settings.targetCapital2040": "رأس المال المستهدف بحلول 2040",
    "settings.targetCapitalDesc": "هدفك المالي لرؤية 2040 (بالريال السعودي)",
    "settings.autoReinvest": "إعادة استثمار الأرباح تلقائيًا",
    "settings.autoReinvestDesc": "إعادة استثمار التوزيعات المستلمة تلقائيًا",
    "settings.platforms": "إدارة المنصات",
    "settings.platformsDesc": "إدارة منصات التمويل الجماعي الخاصة بك",
    "settings.existingPlatforms": "المنصات الحالية",
    "settings.addNewPlatform": "إضافة منصة جديدة",
    "settings.platformNamePlaceholder": "اسم المنصة",
    "settings.other": "أخرى",
    "settings.addPlatform": "إضافة منصة",
    "settings.editPlatform": "تعديل المنصة",
    "settings.deletePlatform": "حذف المنصة",
    "settings.editPlatformComingSoon": "ميزة تعديل المنصة قادمة قريباً",
    "settings.deletePlatformConfirm": "هل أنت متأكد من حذف هذه المنصة؟",
    "settings.deletePlatformWarning": "هذا الإجراء لا يمكن التراجع عنه. تأكد من عدم وجود استثمارات مرتبطة بهذه المنصة.",
    "settings.platformDeleted": "تم حذف المنصة",
    "settings.platformDeletedDesc": "تم إزالة المنصة بنجاح",
    "settings.platformDeleteError": "فشل حذف المنصة",
    "settings.platformHasInvestments": "لا يمكن حذف المنصة: يوجد استثمارات مرتبطة بها",
    "settings.saved": "تم حفظ الإعدادات",
    "settings.savedDesc": "تم تحديث تفضيلاتك بنجاح",
    "settings.saveError": "فشل حفظ الإعدادات",
    "settings.platformAdded": "تمت إضافة المنصة",
    "settings.platformAddedDesc": "تمت إضافة المنصة الجديدة بنجاح",
    "settings.platformAddError": "فشل إضافة المنصة",
    "settings.platformNameRequired": "اسم المنصة مطلوب",
    "settings.security": "الأمان والخصوصية",
    "settings.securityDesc": "احمِ بياناتك المالية بالمصادقة البيومترية",
    "settings.enableSecurity": "تفعيل أمان التطبيق",
    "settings.enableSecurityDesc": "طلب المصادقة عند فتح التطبيق",
    "settings.setupPIN": "إعداد رقم PIN",
    "settings.setupPINDesc": "تعيين رقم PIN من 4-6 أرقام للوصول إلى التطبيق",
    "settings.enterPIN": "أدخل رقم PIN الجديد (4-6 أرقام)",
    "settings.confirmPIN": "تأكيد رقم PIN",
    "settings.setPIN": "تعيين رقم PIN",
    "settings.pinMismatch": "أرقام PIN غير متطابقة",
    "settings.pinTooShort": "يجب أن يكون رقم PIN على الأقل 4 أرقام",
    "settings.pinSet": "تم تعيين رقم PIN بنجاح",
    "settings.pinSetDesc": "تم تكوين رقم PIN الأمني الخاص بك",
    "settings.biometric": "المصادقة البيومترية",
    "settings.biometricDesc": "استخدم بصمة الإصبع أو Face ID لفتح التطبيق",
    "settings.enableBiometric": "تفعيل البيومتري",
    "settings.registerBiometric": "تسجيل البيومتري",
    "settings.biometricNotSupported": "المصادقة البيومترية غير متاحة على هذا الجهاز",
    "settings.biometricRegistered": "تم تسجيل البيومتري",
    "settings.biometricRegisteredDesc": "يمكنك الآن استخدام المصادقة البيومترية",
    "settings.biometricRegisterError": "فشل تسجيل البيومتري",
    
    // Checkpoints
    "checkpoints.title": "نقاط التفتيش للمحفظة",
    "checkpoints.titleDesc": "حفظ واستعادة لقطات كاملة للمحفظة",
    "checkpoints.saveCheckpoint": "حفظ نقطة تفتيش",
    "checkpoints.restoreCheckpoint": "استعادة نقطة تفتيش",
    "checkpoints.deleteCheckpoint": "حذف نقطة تفتيش",
    "checkpoints.checkpointName": "اسم نقطة التفتيش",
    "checkpoints.checkpointNamePlaceholder": "أدخل اسم نقطة التفتيش",
    "checkpoints.createTitle": "إنشاء نقطة تفتيش للمحفظة",
    "checkpoints.createDesc": "حفظ الحالة الحالية لمحفظتك بالكامل",
    "checkpoints.restoreTitle": "استعادة المحفظة",
    "checkpoints.restoreDesc": "سيتم استبدال جميع البيانات الحالية ببيانات نقطة التفتيش. لا يمكن التراجع عن هذا الإجراء.",
    "checkpoints.restoreWarning": "هل أنت متأكد من استعادة نقطة التفتيش هذه؟",
    "checkpoints.deleteWarning": "هل أنت متأكد من حذف نقطة التفتيش هذه؟",
    "checkpoints.saved": "تم حفظ نقطة التفتيش",
    "checkpoints.savedDesc": "تم إنشاء لقطة المحفظة بنجاح",
    "checkpoints.saveError": "فشل حفظ نقطة التفتيش",
    "checkpoints.restored": "تم استعادة المحفظة",
    "checkpoints.restoredDesc": "تم استعادة بيانات المحفظة من نقطة التفتيش",
    "checkpoints.restoreError": "فشلت استعادة نقطة التفتيش",
    "checkpoints.deleted": "تم حذف نقطة التفتيش",
    "checkpoints.deletedDesc": "تمت إزالة نقطة التفتيش",
    "checkpoints.deleteError": "فشل حذف نقطة التفتيش",
    "checkpoints.noCheckpoints": "لا توجد نقاط تفتيش",
    "checkpoints.noCheckpointsDesc": "قم بإنشاء نقطة التفتيش الأولى لحفظ حالة المحفظة",
    "checkpoints.created": "تاريخ الإنشاء",
    "checkpoints.entities": "الكيانات",
    "checkpoints.investments": "الاستثمارات",
    "checkpoints.cashflows": "التدفقات النقدية",
    "checkpoints.size": "الحجم",
    
    // Lock Screen
    "lock.title": "مركز A.Z المالي",
    "lock.subtitle": "رؤية 2040",
    "lock.welcome": "مرحبًا بعودتك",
    "lock.enterPIN": "أدخل رقم PIN الخاص بك لفتح القفل",
    "lock.useBiometric": "استخدام البيومتري",
    "lock.unlock": "فتح القفل",
    "lock.incorrectPIN": "رقم PIN غير صحيح",
    "lock.biometricFailed": "فشلت المصادقة البيومترية",
    "lock.tryAgain": "حاول مرة أخرى أو استخدم رقم PIN",
    
    // Help & Guide
    "help.title": "المساعدة والدليل",
    "help.subtitle": "دليل شامل لاستخدام مركز A.Z المالي",
    "help.gettingStarted": "البدء",
    "help.gettingStartedDesc": "تعلم أساسيات مركز A.Z المالي وكيفية البدء في رحلتك الاستثمارية.",
    "help.addingInvestments": "إضافة الاستثمارات",
    "help.addingInvestmentsDesc": "انتقل إلى صفحة الاستثمارات وانقر على 'إضافة استثمار'. املأ التفاصيل بما في ذلك المنصة والمبلغ (استخدم زر +1000 ريال للراحة)، العائد المتوقع، درجة المخاطرة، والتواريخ. اختر الحالة: نشط (مستمر)، قيد الانتظار (لم يبدأ بعد)، أو مكتمل (منتهي).",
    "help.trackingCashflows": "تتبع التدفقات النقدية",
    "help.trackingCashflowsDesc": "راقب جميع توزيعات الأرباح وعوائد رأس المال في قسم التدفقات النقدية. قم بالتصفية حسب الحالة: مستلم (تم الدفع)، متوقع (مستحق قريبًا)، أو قادم (مجدول).",
    "help.reinvesting": "إعادة استثمار الأرباح",
    "help.reinvestingDesc": "استخدم صفحة إعادة الاستثمار لعرض النقد المتاح من التوزيعات. اختر استثمارًا عالي الأداء وانقر على 'إعادة الاستثمار' لمضاعفة عوائدك بشكل استراتيجي.",
    
    "help.features": "الميزات الرئيسية",
    "help.featuresDesc": "استكشف الميزات القوية لمركز A.Z المالي",
    "help.proLiteMode": "الوضع الاحترافي / المبسط",
    "help.proLiteModeDesc": "التبديل بين الوضع الاحترافي (تحليلات كاملة، تفاصيل شاملة، مخططات متقدمة) والوضع المبسط (عرض مبسط مع 4 مقاييس أساسية فقط). التبديل باستخدام الأيقونة في تذييل الشريط الجانبي.",
    "help.delayTracking": "تتبع التأخير والمتعثرة",
    "help.delayTrackingDesc": "للاستثمارات المكتملة، قم بتعيين تاريخ الانتهاء الفعلي. إذا تأخر عن تاريخ الانتهاء المتوقع، يحسب النظام أيام التأخير. التأخيرات ≥90 يومًا (3 أشهر) تُصنف تلقائيًا كـ 'متعثرة' مع شارة حمراء.",
    "help.quickInput": "الإدخال السريع (+1000 ريال)",
    "help.quickInputDesc": "عند إضافة الاستثمارات، استخدم زر +1000 ريال بجوار حقل المبلغ لإدخال البيانات بسرعة. كل نقرة تضيف 1000 ريال إلى القيمة الحالية.",
    "help.bilingualSupport": "الدعم ثنائي اللغة",
    "help.bilingualSupportDesc": "التبديل بين الإنجليزية والعربية (مع دعم RTL) باستخدام زر تبديل اللغة. يتكيف كل المحتوى، بما في ذلك التواريخ والأرقام، مع اختيارك للغة.",
    
    "help.metrics": "فهم المقاييس",
    "help.metricsDesc": "شرح مؤشرات الأداء الرئيسية",
    "help.totalCapital": "رأس المال الإجمالي",
    "help.totalCapitalDesc": "مجموع جميع مبالغ الاستثمار في محفظتك، بما في ذلك الاستثمارات النشطة والمعلقة والمكتملة.",
    "help.totalReturns": "إجمالي العوائد",
    "help.totalReturnsDesc": "مجموع جميع توزيعات الأرباح المستلمة وعوائد رأس المال من استثماراتك.",
    "help.averageIRR": "متوسط العائد الداخلي",
    "help.averageIRRDesc": "معدل العائد الداخلي - متوسط النسبة المئوية للعائد السنوي المتوقع عبر محفظتك، مرجح حسب مبلغ الاستثمار.",
    "help.progressTo2040": "التقدم نحو 2040",
    "help.progressTo2040Desc": "النسبة المئوية من رأس المال المستهدف في رؤية 2040 المحقق، محسوبة كـ (إجمالي العوائد / رأس المال المستهدف) × 100.",
    "help.availableCash": "النقد المتاح",
    "help.availableCashDesc": "النقد الجاهز لإعادة الاستثمار = الرصيد النقدي الإجمالي ناقص إعادة الاستثمارات النشطة/المعلقة. إعادة الاستثمارات المكتملة تعيد رأس مالها.",
    "help.distressedInvestments": "الاستثمارات المتعثرة",
    "help.distressedInvestmentsDesc": "الاستثمارات المكتملة المتأخرة بـ 3+ أشهر (≥90 يومًا). تحتاج هذه إلى اهتمام وقد تشير إلى مشاكل في المنصة.",
    
    "help.platforms": "المنصات المدعومة",
    "help.platformsDesc": "منصات التمويل الجماعي القائم على الديون المدمجة في النظام",
    "help.sukuk": "صكوك",
    "help.sukukDesc": "منصة استثمارية متوافقة مع الشريعة الإسلامية تقدم سندات وفرص تمويل متوافقة مع الشريعة.",
    "help.manfaa": "منفعة",
    "help.manfaaDesc": "منصة سعودية للتمويل الجماعي للاستثمارات القائمة على الديون مع ملفات مخاطر متنوعة.",
    "help.lendo": "ليندو",
    "help.lendoDesc": "منصة إقراض من نظير إلى نظير تربط المستثمرين بالمقترضين للاستثمارات ذات العائد الثابت.",
    "help.addCustomPlatform": "إضافة منصة مخصصة",
    "help.addCustomPlatformDesc": "انتقل إلى الإعدادات ← إدارة المنصات لإضافة منصات إضافية غير موجودة في القائمة الافتراضية.",
    
    "help.tips": "نصائح وأفضل الممارسات",
    "help.tipsDesc": "قم بتعظيم تجربتك مع هذه النصائح المفيدة",
    "help.tip1": "تحديث تواريخ الانتهاء الفعلية بانتظام",
    "help.tip1Desc": "للاستثمارات المكتملة، قم دائمًا بتعيين تاريخ الانتهاء الفعلي لتتبع التأخيرات وتحديد المنصات الإشكالية.",
    "help.tip2": "مراقبة الاستثمارات المتعثرة",
    "help.tip2Desc": "تحقق من شارات 'متعثرة' الحمراء بانتظام. فكر في تقليل التعرض للمنصات ذات التأخيرات المتكررة.",
    "help.tip3": "استخدام الوضع الاحترافي للتحليل",
    "help.tip3Desc": "قم بالتبديل إلى الوضع الاحترافي عند مراجعة أداء المحفظة للوصول إلى المخططات التفصيلية وتحليلات التدفق النقدي.",
    "help.tip4": "إعادة الاستثمار بشكل استراتيجي",
    "help.tip4Desc": "استخدم صفحة إعادة الاستثمار لتحديد الفرص ذات الأداء الأفضل المرتبة حسب العائد المتوقع قبل نشر النقد المتاح.",
    "help.tip5": "تحديد أهداف واقعية",
    "help.tip5Desc": "في الإعدادات، قم بتكوين رأس المال المستهدف لرؤية 2040 لتتبع التقدم نحو أهدافك المالية.",
    
    "help.settings": "الإعدادات والتخصيص",
    "help.settingsDesc": "خصص تجربة مركزك الاستثماري",
    "help.appearance": "إعدادات المظهر",
    "help.appearanceDesc": "خصص المظهر (فاتح/داكن)، حجم الخط (صغير/متوسط/كبير)، ووضع العرض. قم بالتبديل بين الوضع الاحترافي (تحليلات كاملة) والوضع المبسط (4 مقاييس أساسية) لتتناسب مع تفضيلك.",
    "help.languageSettings": "اللغة والمنطقة",
    "help.languageSettingsDesc": "التبديل بين الإنجليزية والعربية مع دعم RTL الكامل. العملة حاليًا هي الريال السعودي فقط. جميع التواريخ والأرقام والنصوص تتكيف مع اختيارك للغة.",
    "help.investmentGoalsSettings": "الأهداف الاستثمارية",
    "help.investmentGoalsSettingsDesc": "حدد رأس المال المستهدف لرؤية 2040 لتتبع التقدم المالي طويل الأجل. قم بتفعيل إعادة الاستثمار التلقائي لنشر التوزيعات المستلمة تلقائيًا في فرص جديدة.",
    "help.platformManagement": "إدارة المنصات",
    "help.platformManagementDesc": "عرض المنصات الحالية (صكوك، منفعة، ليندو) وإضافة منصات مخصصة. أدخل اسم المنصة واختر النوع (صكوك/منفعة/ليندو/أخرى) لتوسيع نطاق استثماراتك.",
    
    // Auth & Login
    "login": "تسجيل الدخول",
    "loginDescription": "أدخل بيانات الاعتماد للوصول إلى مركز A.Z المالي",
    "username": "اسم المستخدم",
    "password": "كلمة المرور",
    "enterUsername": "أدخل اسم المستخدم",
    "enterPassword": "أدخل كلمة المرور",
    "loggingIn": "جارٍ تسجيل الدخول...",
    "loginSuccess": "تم تسجيل الدخول بنجاح",
    "loginFailed": "فشل تسجيل الدخول",
    "invalidCredentials": "اسم المستخدم أو كلمة المرور غير صحيحة",
    "pleaseEnterCredentials": "يرجى إدخال اسم المستخدم وكلمة المرور",
    "error": "خطأ",
    "success": "نجح",
    
    // User Management
    "userManagement": "إدارة المستخدمين",
    "manageUsersAndRoles": "إدارة المستخدمين والأدوار والصلاحيات",
    "addUser": "إضافة مستخدم",
    "editUser": "تعديل مستخدم",
    "allUsers": "جميع المستخدمين",
    "totalUsers": "إجمالي المستخدمين",
    "noUsersFound": "لم يتم العثور على مستخدمين",
    "name": "الاسم",
    "fullName": "الاسم الكامل",
    "email": "البريد الإلكتروني",
    "phone": "الهاتف",
    "role": "الدور",
    "status": "الحالة",
    "actions": "الإجراءات",
    "active": "نشط",
    "inactive": "غير نشط",
    "noRole": "بدون دور",
    "selectRole": "اختر دور",
    "newPassword": "كلمة المرور الجديدة (اتركها فارغة للإبقاء على الحالية)",
    "activeStatus": "حالة النشاط",
    "activeStatusDescription": "يمكن للمستخدم تسجيل الدخول عندما يكون نشطاً",
    "cancel": "إلغاء",
    "save": "حفظ",
    "saving": "جاري الحفظ...",
    "delete": "حذف",
    "deleting": "جاري الحذف...",
    "confirmDelete": "تأكيد الحذف",
    "deleteUserConfirmation": "هل أنت متأكد من حذف المستخدم",
    "userCreated": "تم إنشاء المستخدم بنجاح",
    "userUpdated": "تم تحديث المستخدم بنجاح",
    "userDeleted": "تم حذف المستخدم بنجاح",
    "userCreationFailed": "فشل إنشاء المستخدم",
    "userUpdateFailed": "فشل تحديث المستخدم",
    "userDeletionFailed": "فشل حذف المستخدم",
    "impersonationStarted": "الآن تعمل كالمستخدم المحدد",
    "impersonationFailed": "فشل بدء الانتحال",
    "impersonationActive": "أنت الآن تعمل كمستخدم آخر",
    "endImpersonation": "إنهاء الانتحال",
    "impersonationEnded": "تم إنهاء الانتحال بنجاح",
    "impersonationEndFailed": "فشل إنهاء الانتحال",
    "addUserDescription": "إنشاء حساب مستخدم جديد",
    "editUserDescription": "تحديث تفاصيل المستخدم والصلاحيات",
    "accessDenied": "تم رفض الوصول",
    "noPermissionToViewUsers": "ليس لديك صلاحية لعرض هذه الصفحة",
    "loading": "جاري التحميل...",
    
    // Role Management
    "roleManagement": "إدارة الأدوار",
    "manageRolesAndPermissions": "إدارة أدوار النظام وصلاحياتها",
    "addRole": "إضافة دور",
    "editRole": "تعديل دور",
    "allRoles": "جميع الأدوار",
    "totalRoles": "إجمالي الأدوار",
    "totalPermissions": "إجمالي الصلاحيات",
    "noRolesFound": "لم يتم العثور على أدوار",
    "roleName": "اسم الدور",
    "displayNameEnglish": "الاسم المعروض (إنجليزي)",
    "displayNameArabic": "الاسم المعروض (عربي)",
    "description": "الوصف",
    "permissions": "الصلاحيات",
    "permissionsCount": "صلاحيات",
    "users": "المستخدمون",
    "viewAndManageSystemRoles": "عرض وإدارة أدوار النظام",
    "roleCreated": "تم إنشاء الدور بنجاح",
    "roleUpdated": "تم تحديث الدور بنجاح",
    "roleDeleted": "تم حذف الدور بنجاح",
    "roleCreationFailed": "فشل إنشاء الدور",
    "roleUpdateFailed": "فشل تحديث الدور",
    "roleDeletionFailed": "فشل حذف الدور",
    "deleteRoleConfirmation": "هل أنت متأكد من حذف الدور",
    "addRoleDescription": "إنشاء دور جديد بصلاحيات مخصصة",
    "editRoleDescription": "تحديث تفاصيل الدور والصلاحيات",
    "noPermissionToViewRoles": "ليس لديك صلاحية لعرض هذه الصفحة",
    
    // Permission Categories
    "permissionCategory.user": "إدارة المستخدمين",
    "permissionCategory.role": "إدارة الأدوار",
    "permissionCategory.investment": "إدارة الاستثمارات",
    "permissionCategory.cashflow": "إدارة التدفقات النقدية",
    "permissionCategory.analytics": "التحليلات",
    "permissionCategory.audit": "التدقيق",
    "permissionCategory.platform": "المنصات",
    "permissionCategory.settings": "الإعدادات",
    "permissionCategory.advanced": "الميزات المتقدمة",
    "permissionCategory.alerts": "التنبيهات",
    "permissionCategory.data": "إدارة البيانات",
    
    // Individual Permissions
    "permission.USER_MANAGE": "إدارة المستخدمين",
    "permission.USER_CREATE": "إنشاء مستخدمين",
    "permission.USER_EDIT": "تعديل المستخدمين",
    "permission.USER_DELETE": "حذف المستخدمين",
    "permission.USER_VIEW_SENSITIVE": "عرض بيانات المستخدم الحساسة",
    "permission.ROLE_MANAGE": "إدارة الأدوار",
    "permission.ROLE_CREATE": "إنشاء أدوار",
    "permission.ROLE_EDIT": "تعديل الأدوار",
    "permission.ROLE_DELETE": "حذف الأدوار",
    "permission.INVESTMENT_VIEW": "عرض الاستثمارات",
    "permission.INVESTMENT_CREATE": "إنشاء استثمارات",
    "permission.INVESTMENT_EDIT": "تعديل الاستثمارات",
    "permission.INVESTMENT_DELETE": "حذف الاستثمارات",
    "permission.INVESTMENT_APPROVE": "الموافقة على الاستثمارات",
    "permission.CASHFLOW_VIEW": "عرض التدفقات النقدية",
    "permission.CASHFLOW_CREATE": "إنشاء تدفقات نقدية",
    "permission.CASHFLOW_EDIT": "تعديل التدفقات النقدية",
    "permission.CASHFLOW_DELETE": "حذف التدفقات النقدية",
    "permission.ANALYTICS_VIEW": "عرض التحليلات",
    "permission.ANALYTICS_EXPORT": "تصدير التحليلات",
    "permission.AUDIT_VIEW": "عرض سجلات التدقيق",
    "permission.AUDIT_EXPORT": "تصدير سجلات التدقيق",
    "permission.PLATFORM_MANAGE": "إدارة المنصات",
    "permission.SETTINGS_MANAGE": "إدارة الإعدادات",
    "permission.IMPERSONATE": "انتحال المستخدمين",
    "permission.APPROVE_EXPORTS": "الموافقة على طلبات التصدير",
    "permission.APPROVE_VIEWS": "الموافقة على طلبات العرض",
    "permission.TEMPORARY_ROLE_ASSIGN": "تعيين أدوار مؤقتة",
    "permission.FIELD_MASKING_OVERRIDE": "تجاوز إخفاء الحقول",
    "permission.ALERT_MANAGE": "إدارة التنبيهات",
    "permission.DATA_EXPORT": "تصدير البيانات",
  },
};

export function LanguageProvider({ children, defaultLanguage = "en" }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(
    () => (localStorage.getItem("language") as Language) || defaultLanguage
  );

  useEffect(() => {
    const root = document.documentElement;
    root.setAttribute("lang", language);
    root.setAttribute("dir", "rtl");
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageProviderContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageProviderContext.Provider>
  );
}
