import { BarChart3, Building2, TrendingUp, Calendar, DollarSign, Calculator, Zap, LayoutGrid, Wallet, Percent, Droplet, Target, Activity, CheckCircle, Clock, XCircle, PieChart } from "lucide-react";
import type { WidgetDefinition, WidgetId } from "@/types/widgets";
import { StatsOverviewWidget } from "./stats-overview-widget";
import { PlatformCardsWidget } from "./platform-cards-widget";
import { PortfolioChartWidget } from "./portfolio-chart-widget";
import { 
  PortfolioValueWidget,
  CashAvailableWidget,
  ReturnsRatioWidget,
  CashRatioWidget,
  PortfolioAPRWidget,
  PortfolioROIWidget,
  AvgDurationWidget,
  AvgAmountWidget,
  TotalInvestmentsWidget,
  ActiveInvestmentsWidget,
  CompletedInvestmentsWidget,
  LateInvestmentsWidget,
  DefaultedInvestmentsWidget,
} from "./metric-widgets";
import { StatusPieChartWidget } from "./status-pie-chart-widget";
import { PlatformPieChartWidget } from "./platform-pie-chart-widget";

// Widget registry - all available widgets
export const WIDGET_REGISTRY: Record<WidgetId, WidgetDefinition> = {
  'stats-overview': {
    id: 'stats-overview',
    title: 'Portfolio Overview',
    titleAr: 'نظرة عامة على المحفظة',
    description: 'Key portfolio statistics',
    descriptionAr: 'إحصائيات المحفظة الرئيسية',
    defaultLayout: { i: 'stats-overview', x: 0, y: 0, w: 12, h: 2, minW: 6, minH: 2 },
    component: StatsOverviewWidget,
    icon: LayoutGrid,
    category: 'stats',
  },
  'platform-cards': {
    id: 'platform-cards',
    title: 'Platform Overview',
    titleAr: 'نظرة على المنصات',
    description: 'Investment platforms summary',
    descriptionAr: 'ملخص منصات الاستثمار',
    defaultLayout: { i: 'platform-cards', x: 0, y: 2, w: 12, h: 4, minW: 6, minH: 3 },
    component: PlatformCardsWidget,
    icon: Building2,
    category: 'stats',
  },
  'portfolio-chart': {
    id: 'portfolio-chart',
    title: 'Portfolio Performance',
    titleAr: 'أداء المحفظة',
    description: 'Performance chart over time',
    descriptionAr: 'رسم بياني للأداء عبر الوقت',
    defaultLayout: { i: 'portfolio-chart', x: 0, y: 6, w: 8, h: 5, minW: 6, minH: 4 },
    component: PortfolioChartWidget,
    icon: BarChart3,
    category: 'charts',
  },
  'upcoming-cashflows': {
    id: 'upcoming-cashflows',
    title: 'Upcoming Cashflows',
    titleAr: 'التدفقات النقدية القادمة',
    description: 'Expected payments',
    descriptionAr: 'المدفوعات المتوقعة',
    defaultLayout: { i: 'upcoming-cashflows', x: 8, y: 6, w: 4, h: 4, minW: 4, minH: 3 },
    component: () => <div>Upcoming Cashflows (TODO)</div>,
    icon: Calendar,
    category: 'stats',
  },
  'recent-investments': {
    id: 'recent-investments',
    title: 'Recent Investments',
    titleAr: 'الاستثمارات الأخيرة',
    description: 'Latest investments',
    descriptionAr: 'آخر الاستثمارات',
    defaultLayout: { i: 'recent-investments', x: 0, y: 10, w: 12, h: 3, minW: 6, minH: 2 },
    component: () => <div>Recent Investments (TODO)</div>,
    icon: TrendingUp,
    category: 'stats',
  },
  'cash-balance': {
    id: 'cash-balance',
    title: 'Cash Balance',
    titleAr: 'الرصيد النقدي',
    description: 'Available cash',
    descriptionAr: 'النقد المتاح',
    defaultLayout: { i: 'cash-balance', x: 0, y: 13, w: 4, h: 2, minW: 3, minH: 2 },
    component: () => <div>Cash Balance (TODO)</div>,
    icon: DollarSign,
    category: 'professional',
    requiredMode: 'professional',
  },
  'goal-calculator': {
    id: 'goal-calculator',
    title: 'Goal Calculator',
    titleAr: 'حاسبة الهدف',
    description: 'Investment goal projections',
    descriptionAr: 'توقعات الهدف الاستثماري',
    defaultLayout: { i: 'goal-calculator', x: 4, y: 13, w: 8, h: 4, minW: 6, minH: 3 },
    component: () => <div>Goal Calculator (TODO)</div>,
    icon: Calculator,
    category: 'professional',
    requiredMode: 'professional',
  },
  'quick-actions': {
    id: 'quick-actions',
    title: 'Quick Actions',
    titleAr: 'إجراءات سريعة',
    description: 'Common actions',
    descriptionAr: 'الإجراءات الشائعة',
    defaultLayout: { i: 'quick-actions', x: 0, y: 17, w: 12, h: 2, minW: 4, minH: 2 },
    component: () => <div>Quick Actions (TODO)</div>,
    icon: Zap,
    category: 'actions',
  },
  // New financial metric widgets
  'portfolio-value': {
    id: 'portfolio-value',
    title: 'Portfolio Value',
    titleAr: 'قيمة المحفظة',
    description: 'Total portfolio value',
    descriptionAr: 'إجمالي قيمة المحفظة',
    defaultLayout: { i: 'portfolio-value', x: 0, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
    component: PortfolioValueWidget,
    icon: Wallet,
    category: 'metrics',
  },
  'cash-available': {
    id: 'cash-available',
    title: 'Cash Available',
    titleAr: 'الكاش المتاح',
    description: 'Available cash balance',
    descriptionAr: 'الرصيد النقدي المتاح',
    defaultLayout: { i: 'cash-available', x: 3, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
    component: CashAvailableWidget,
    icon: DollarSign,
    category: 'metrics',
  },
  'returns-ratio': {
    id: 'returns-ratio',
    title: 'Returns Ratio',
    titleAr: 'نسبة العائد',
    description: 'Actual vs Expected returns',
    descriptionAr: 'العائد المحقق مقابل المتوقع',
    defaultLayout: { i: 'returns-ratio', x: 6, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
    component: ReturnsRatioWidget,
    icon: TrendingUp,
    category: 'metrics',
  },
  'cash-ratio': {
    id: 'cash-ratio',
    title: 'Cash Ratio',
    titleAr: 'نسبة الكاش',
    description: 'Cash to portfolio ratio',
    descriptionAr: 'نسبة الكاش للمحفظة',
    defaultLayout: { i: 'cash-ratio', x: 9, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
    component: CashRatioWidget,
    icon: Droplet,
    category: 'metrics',
  },
  'portfolio-apr': {
    id: 'portfolio-apr',
    title: 'Portfolio APR',
    titleAr: 'العائد السنوي',
    description: 'Annual percentage rate',
    descriptionAr: 'معدل العائد السنوي',
    defaultLayout: { i: 'portfolio-apr', x: 0, y: 2, w: 3, h: 2, minW: 2, minH: 2 },
    component: PortfolioAPRWidget,
    icon: Percent,
    category: 'metrics',
  },
  'portfolio-roi': {
    id: 'portfolio-roi',
    title: 'Portfolio ROI',
    titleAr: 'العائد على الاستثمار',
    description: 'Return on investment',
    descriptionAr: 'العائد على الاستثمار',
    defaultLayout: { i: 'portfolio-roi', x: 3, y: 2, w: 3, h: 2, minW: 2, minH: 2 },
    component: PortfolioROIWidget,
    icon: Target,
    category: 'metrics',
  },
  'avg-duration': {
    id: 'avg-duration',
    title: 'Avg Duration',
    titleAr: 'متوسط المدة',
    description: 'Average investment duration',
    descriptionAr: 'متوسط مدة الاستثمار',
    defaultLayout: { i: 'avg-duration', x: 6, y: 2, w: 3, h: 2, minW: 2, minH: 2 },
    component: AvgDurationWidget,
    icon: Calendar,
    category: 'metrics',
  },
  'avg-amount': {
    id: 'avg-amount',
    title: 'Avg Amount',
    titleAr: 'متوسط القيمة',
    description: 'Average investment amount',
    descriptionAr: 'متوسط قيمة الاستثمار',
    defaultLayout: { i: 'avg-amount', x: 9, y: 2, w: 3, h: 2, minW: 2, minH: 2 },
    component: AvgAmountWidget,
    icon: DollarSign,
    category: 'metrics',
  },
  'total-investments': {
    id: 'total-investments',
    title: 'Total Investments',
    titleAr: 'إجمالي الاستثمارات',
    description: 'Total number of investments',
    descriptionAr: 'العدد الإجمالي للاستثمارات',
    defaultLayout: { i: 'total-investments', x: 0, y: 4, w: 2, h: 2, minW: 2, minH: 2 },
    component: TotalInvestmentsWidget,
    icon: Activity,
    category: 'counters',
  },
  'active-investments': {
    id: 'active-investments',
    title: 'Active',
    titleAr: 'نشطة',
    description: 'Active investments',
    descriptionAr: 'الاستثمارات النشطة',
    defaultLayout: { i: 'active-investments', x: 2, y: 4, w: 2, h: 2, minW: 2, minH: 2 },
    component: ActiveInvestmentsWidget,
    icon: Activity,
    category: 'counters',
  },
  'completed-investments': {
    id: 'completed-investments',
    title: 'Completed',
    titleAr: 'منتهية',
    description: 'Completed investments',
    descriptionAr: 'الاستثمارات المنتهية',
    defaultLayout: { i: 'completed-investments', x: 4, y: 4, w: 2, h: 2, minW: 2, minH: 2 },
    component: CompletedInvestmentsWidget,
    icon: CheckCircle,
    category: 'counters',
  },
  'late-investments': {
    id: 'late-investments',
    title: 'Late',
    titleAr: 'متأخرة',
    description: 'Late investments',
    descriptionAr: 'الاستثمارات المتأخرة',
    defaultLayout: { i: 'late-investments', x: 6, y: 4, w: 2, h: 2, minW: 2, minH: 2 },
    component: LateInvestmentsWidget,
    icon: Clock,
    category: 'counters',
  },
  'defaulted-investments': {
    id: 'defaulted-investments',
    title: 'Defaulted',
    titleAr: 'متعثرة',
    description: 'Defaulted investments',
    descriptionAr: 'الاستثمارات المتعثرة',
    defaultLayout: { i: 'defaulted-investments', x: 8, y: 4, w: 2, h: 2, minW: 2, minH: 2 },
    component: DefaultedInvestmentsWidget,
    icon: XCircle,
    category: 'counters',
  },
  'status-pie-chart': {
    id: 'status-pie-chart',
    title: 'Status Distribution',
    titleAr: 'توزيع الحالات',
    description: 'Investment status breakdown',
    descriptionAr: 'توزيع حالات الاستثمار',
    defaultLayout: { i: 'status-pie-chart', x: 0, y: 6, w: 6, h: 5, minW: 4, minH: 4 },
    component: StatusPieChartWidget,
    icon: PieChart,
    category: 'charts',
  },
  'platform-pie-chart': {
    id: 'platform-pie-chart',
    title: 'Platform Distribution',
    titleAr: 'توزيع المنصات',
    description: 'Investment distribution by platform',
    descriptionAr: 'توزيع الاستثمارات حسب المنصة',
    defaultLayout: { i: 'platform-pie-chart', x: 6, y: 6, w: 6, h: 5, minW: 4, minH: 4 },
    component: PlatformPieChartWidget,
    icon: Building2,
    category: 'charts',
  },
};

export function getDefaultLayout(): WidgetDefinition['defaultLayout'][] {
  // Return deep copy to prevent mutations
  return Object.values(WIDGET_REGISTRY).map(widget => ({ ...widget.defaultLayout }));
}

export function getAvailableWidgets(viewMode: 'simple' | 'professional' = 'simple'): WidgetDefinition[] {
  return Object.values(WIDGET_REGISTRY).filter(widget => {
    if (!widget.requiredMode) return true;
    return widget.requiredMode === viewMode || viewMode === 'professional';
  });
}
